allowBuilds:
  "@swc/core": true
  esbuild: true
  msw: false
  unrs-resolver: true
blockExoticSubdeps: true
minimumReleaseAge: 4320
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
engineStrict: true
pmOnFail: error
strictDepBuilds: true
strictPeerDependencies: true
catalog:
  vite: 8.1.3
  "@vitest/expect": 4.1.9
overrides:
  # Storybook currently uses @vitest/expect 3.2.4 which doesn't work with our vitest.d.ts
  "@vitest/expect": "catalog:"
  # @codecov/vite-plugin does not have official support for Vite 8, but works:
  # https://github.com/codecov/codecov-javascript-bundler-plugins/issues/264
  "vite": "catalog:"
  # Fix GHSA-gv7w-rqvm-qjhr, GHSA-g7r4-m6w7-qqqr
  esbuild@>=0.17.0 <0.28.1: ">=0.28.1"
