allowBuilds:
  "@swc/core": true
  esbuild: true
  msw: false
  unrs-resolver: true
blockExoticSubdeps: true
minimumReleaseAge: 4320
trustPolicy: no-downgrade
engineStrict: true
packageManagerStrict: true
packageManagerStrictVersion: true
strictDepBuilds: true
strictPeerDependencies: true
overrides:
  # Storybook currently uses @vitest/expect 3.2.4 which doesn't work with our vitest.d.ts
  "@vitest/expect": "$@vitest/expect"
  # @codecov/vite-plugin does not have official support for Vite 8, but works:
  # https://github.com/codecov/codecov-javascript-bundler-plugins/issues/264
  "vite": "$vite"
