#!/bin/bash

if [ -n "$1" ]
then
  git checkout "$1"
fi

echo "Building frontend..."

npm run build --prefix frontend

echo "Building and running backend..."

pushd "backend" > /dev/null 2>&1
cargo sqlx database reset -y
ASSET_DIR="$PWD/../frontend/dist" cargo run --release --features memory-serve -- -s
popd > /dev/null 2>&1
