#!/bin/bash

if [ -n "$1" ]
then
  git checkout "$1"
fi

# Exit on errors
set -e

# Print the commands as they are executed
set -x

echo "Building frontend..."

pushd "frontend" > /dev/null 2>&1
npm install
npm run build
popd > /dev/null 2>&1

echo "Building and running backend..."

pushd "backend" > /dev/null 2>&1
cargo sqlx database reset -y
ASSET_DIR="$PWD/../frontend/dist" cargo run --release --features memory-serve -- -s
popd > /dev/null 2>&1
