codecov:
  notify:
    after_n_builds: 2
comment:
    require_bundle_changes: True
    bundle_change_threshold: "50Kb"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
