services:
  backend:
    image: ghcr.io/tweedegolf/rust-dev:stable-browser
    ports:
      - "8080:8080"
    # user: "${DOCKER_USER:-${USER_ID:-${UID:-0}}:${GROUP_ID:-${GID:-0}}}"
    environment:
      TZ: "Europe/Amsterdam"
      CARGO_HOME: .cargo
      CARGO_TARGET_DIR: "./target-docker"
      PLAYWRIGHT_BROWSERS_PATH: "/abacus/.cache/ms-playwright"
    volumes:
      - ".:/abacus"
    working_dir: /abacus/backend
    command: ["cargo", "watch", "--why", "--ignore", ".cargo", "--ignore", "db.sqlite*", "--ignore", "target-docker", "-x", "run --"]

  frontend:
    depends_on: [backend]
    image: node:20
    ports:
      - 3000:3000
    volumes:
      - ".:/abacus"
    working_dir: /abacus/frontend
    # user: "${DOCKER_USER:-${USER_ID:-${UID:-0}}:${GROUP_ID:-${GID:-0}}}"
    environment:
      TZ: "Europe/Amsterdam"
      API_HOST: http://backend:8080
      VITE_HOST: "0.0.0.0"
      PLAYWRIGHT_BROWSERS_PATH: "/abacus/.cache/ms-playwright"
    command: ["npm", "run", "dev:docker"]
