#!/bin/bash

# Exit on errors
set -e

if [ -n "$1" ]
then
  git fetch
  git checkout "$1"
  git pull --ff-only
fi

# Print the commands as they are executed
set -x

echo "Building frontend..."

pushd "frontend" > /dev/null 2>&1
npm ci
npm run build
popd > /dev/null 2>&1

echo "Building and running backend..."

pushd "backend" > /dev/null 2>&1
cargo sqlx database reset -y
cargo run --features memory-serve -- -s
popd > /dev/null 2>&1
