import { Election, ElectionSummary, SeatAssignmentResult } from "@/api";

export const seat_assignment: SeatAssignmentResult = {
  seats: 15,
  full_seats: 12,
  residual_seats: 3,
  quota: {
    integer: 340,
    numerator: 4,
    denominator: 15,
  },
  steps: [
    {
      residual_seat_number: 1,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_pg_number: 2,
        pg_options: [2],
        pg_assigned: [2],
        remainder_votes: {
          integer: 296,
          numerator: 7,
          denominator: 15,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 2571,
          remainder_votes: {
            integer: 189,
            numerator: 2,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 321,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 7,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 977,
          remainder_votes: {
            integer: 296,
            numerator: 7,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 325,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          pg_number: 3,
          votes_cast: 567,
          remainder_votes: {
            integer: 226,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 283,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 4,
          votes_cast: 536,
          remainder_votes: {
            integer: 195,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 268,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 453,
          remainder_votes: {
            integer: 112,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 226,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 2,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_pg_number: 3,
        pg_options: [3],
        pg_assigned: [3],
        remainder_votes: {
          integer: 226,
          numerator: 11,
          denominator: 15,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 2571,
          remainder_votes: {
            integer: 189,
            numerator: 2,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 321,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 7,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 977,
          remainder_votes: {
            integer: 296,
            numerator: 7,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 244,
            numerator: 1,
            denominator: 4,
          },
          full_seats: 2,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 567,
          remainder_votes: {
            integer: 226,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 283,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 4,
          votes_cast: 536,
          remainder_votes: {
            integer: 195,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 268,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 453,
          remainder_votes: {
            integer: 112,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 226,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 3,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_pg_number: 4,
        pg_options: [4],
        pg_assigned: [4],
        remainder_votes: {
          integer: 195,
          numerator: 11,
          denominator: 15,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 2571,
          remainder_votes: {
            integer: 189,
            numerator: 2,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 321,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 7,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 977,
          remainder_votes: {
            integer: 296,
            numerator: 7,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 244,
            numerator: 1,
            denominator: 4,
          },
          full_seats: 2,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 567,
          remainder_votes: {
            integer: 226,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 189,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 536,
          remainder_votes: {
            integer: 195,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 268,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 453,
          remainder_votes: {
            integer: 112,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 226,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
    {
      change: {
        changed_by: "AbsoluteMajorityReassignment",
        pg_retracted_seat: 4,
        pg_assigned_seat: 1,
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 2571,
          remainder_votes: {
            integer: 189,
            numerator: 2,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 321,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 7,
          residual_seats: 1,
        },
        {
          pg_number: 2,
          votes_cast: 977,
          remainder_votes: {
            integer: 296,
            numerator: 7,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 244,
            numerator: 1,
            denominator: 4,
          },
          full_seats: 2,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 567,
          remainder_votes: {
            integer: 226,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 189,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 536,
          remainder_votes: {
            integer: 195,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 178,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 453,
          remainder_votes: {
            integer: 112,
            numerator: 11,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 226,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
  ],
  final_standing: [
    {
      pg_number: 1,
      votes_cast: 2571,
      remainder_votes: {
        integer: 189,
        numerator: 2,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 7,
      residual_seats: 1,
      total_seats: 8,
    },
    {
      pg_number: 2,
      votes_cast: 977,
      remainder_votes: {
        integer: 296,
        numerator: 7,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 1,
      total_seats: 3,
    },
    {
      pg_number: 3,
      votes_cast: 567,
      remainder_votes: {
        integer: 226,
        numerator: 11,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 4,
      votes_cast: 536,
      remainder_votes: {
        integer: 195,
        numerator: 11,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 0,
      total_seats: 1,
    },
    {
      pg_number: 5,
      votes_cast: 453,
      remainder_votes: {
        integer: 112,
        numerator: 11,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 0,
      total_seats: 1,
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 5104,
    proxy_certificate_count: 1,
    voter_card_count: 0,
    total_admitted_voters_count: 5105,
  },
  votes_counts: {
    votes_candidates_count: 5104,
    blank_votes_count: 0,
    invalid_votes_count: 1,
    total_votes_cast_count: 5105,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    fewer_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    unreturned_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    too_few_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    too_many_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    other_explanation_count: {
      count: 0,
      polling_stations: [],
    },
    no_explanation_count: {
      count: 0,
      polling_stations: [],
    },
  },
  recounted_polling_stations: [],
  political_group_votes: [
    {
      number: 1,
      total: 2571,
      candidate_votes: [
        {
          number: 1,
          votes: 1069,
        },
        {
          number: 2,
          votes: 303,
        },
        {
          number: 3,
          votes: 321,
        },
        {
          number: 4,
          votes: 210,
        },
        {
          number: 5,
          votes: 36,
        },
        {
          number: 6,
          votes: 101,
        },
        {
          number: 7,
          votes: 79,
        },
        {
          number: 8,
          votes: 121,
        },
        {
          number: 9,
          votes: 150,
        },
        {
          number: 10,
          votes: 149,
        },
        {
          number: 11,
          votes: 15,
        },
        {
          number: 12,
          votes: 17,
        },
      ],
    },
    {
      number: 2,
      total: 977,
      candidate_votes: [
        {
          number: 1,
          votes: 452,
        },
        {
          number: 2,
          votes: 39,
        },
        {
          number: 3,
          votes: 81,
        },
        {
          number: 4,
          votes: 76,
        },
        {
          number: 5,
          votes: 35,
        },
        {
          number: 6,
          votes: 109,
        },
        {
          number: 7,
          votes: 29,
        },
        {
          number: 8,
          votes: 25,
        },
        {
          number: 9,
          votes: 17,
        },
        {
          number: 10,
          votes: 6,
        },
        {
          number: 11,
          votes: 18,
        },
        {
          number: 12,
          votes: 9,
        },
        {
          number: 13,
          votes: 25,
        },
        {
          number: 14,
          votes: 30,
        },
        {
          number: 15,
          votes: 5,
        },
        {
          number: 16,
          votes: 18,
        },
        {
          number: 17,
          votes: 3,
        },
      ],
    },
    {
      number: 3,
      total: 567,
      candidate_votes: [
        {
          number: 1,
          votes: 229,
        },
        {
          number: 2,
          votes: 63,
        },
        {
          number: 3,
          votes: 65,
        },
        {
          number: 4,
          votes: 9,
        },
        {
          number: 5,
          votes: 10,
        },
        {
          number: 6,
          votes: 58,
        },
        {
          number: 7,
          votes: 29,
        },
        {
          number: 8,
          votes: 50,
        },
        {
          number: 9,
          votes: 6,
        },
        {
          number: 10,
          votes: 11,
        },
        {
          number: 11,
          votes: 37,
        },
      ],
    },
    {
      number: 4,
      total: 536,
      candidate_votes: [
        {
          number: 1,
          votes: 347,
        },
        {
          number: 2,
          votes: 33,
        },
        {
          number: 3,
          votes: 14,
        },
        {
          number: 4,
          votes: 82,
        },
        {
          number: 5,
          votes: 30,
        },
        {
          number: 6,
          votes: 30,
        },
      ],
    },
    {
      number: 5,
      total: 453,
      candidate_votes: [
        {
          number: 1,
          votes: 266,
        },
        {
          number: 2,
          votes: 36,
        },
        {
          number: 3,
          votes: 39,
        },
        {
          number: 4,
          votes: 36,
        },
        {
          number: 5,
          votes: 38,
        },
        {
          number: 6,
          votes: 38,
        },
      ],
    },
  ],
};

export const election: Election = {
  id: 4,
  name: "Test Election Absolute Majority Change",
  location: "Test Location",
  number_of_voters: 6000,
  category: "Municipal",
  number_of_seats: 15,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  status: "DataEntryFinished",
  political_groups: [
    {
      number: 1,
      name: "Political Group A",
      candidates: [
        {
          number: 1,
          initials: "L.",
          first_name: "Lidewij",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Johan",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "M.",
          first_name: "Marijke",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "A.",
          first_name: "Arie",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "H.",
          first_name: "Henk",
          last_name: "Van der Weijden",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Berta",
          last_name: "Van der Weijden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 7,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 8,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 9,
          initials: "J.",
          first_name: "Johan",
          last_name: "De Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "M.",
          first_name: "Marijke",
          last_name: "Van den Berg",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 11,
          initials: "R.",
          first_name: "Rolf",
          last_name: "De Jong",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 12,
          initials: "K.",
          first_name: "Karin",
          last_name: "Kok",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 2,
      name: "Political Group B",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tinus",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "D.",
          first_name: "Drs.",
          last_name: "P.",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Willem",
          last_name: "de Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Kloosterboer",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "L.",
          first_name: "Liesbeth",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 6,
          initials: "H.",
          first_name: "Henk",
          last_name: "Van den Berg",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 7,
          initials: "A.",
          first_name: "Adelbert",
          last_name: "Van Doorn",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 8,
          initials: "M.",
          first_name: "Margriet",
          last_name: "Van der Linden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 9,
          initials: "P.",
          first_name: "Paul",
          last_name: "Veldkamp",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "S.",
          first_name: "Sophie",
          last_name: "De Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 11,
          initials: "R.",
          first_name: "Rik",
          last_name: "De Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 12,
          initials: "N.",
          first_name: "Nico",
          last_name: "Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 13,
          initials: "G.",
          first_name: "Gerard",
          last_name: "Bogaert",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 14,
          initials: "J.",
          first_name: "Jan",
          last_name: "Stevens",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 15,
          initials: "E.",
          first_name: "Els",
          last_name: "Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 16,
          initials: "B.",
          first_name: "Bart",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 17,
          initials: "F.",
          first_name: "Frits",
          last_name: "Veldman",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 3,
      name: "Political Group C",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Eva",
          last_name: "Koster",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "L.",
          first_name: "Leon",
          last_name: "Hofman",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Visser",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "D.",
          first_name: "Dirk",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "P.",
          first_name: "Piet",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 7,
          initials: "A.",
          first_name: "Annelies",
          last_name: "Van Loon",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 8,
          initials: "T.J.",
          first_name: "Tessa",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 9,
          initials: "H.J.",
          first_name: "Hans",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "W.J.",
          first_name: "Willem",
          last_name: "Janssen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 11,
          initials: "B.",
          first_name: "Bert",
          last_name: "Meyer",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 4,
      name: "Political Group D",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Hans",
          last_name: "Van der Vaart",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.H.",
          first_name: "Tjolkse Hendrika",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "H.",
          first_name: "Hendrik",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "F.",
          first_name: "Frank",
          last_name: "Van Putten",
          locality: "Test Location",
        },
      ],
    },
    {
      number: 5,
      name: "Political Group E",
      candidates: [
        {
          number: 1,
          initials: "F.",
          first_name: "Frederik",
          last_name: "Jacobse",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.J.",
          first_name: "Tedje Johannes",
          last_name: "van Es",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "K.",
          first_name: "Karel",
          last_name: "van Es",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.",
          first_name: "Tilly",
          last_name: "van Yvonne",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "W.",
          first_name: "Willy",
          last_name: "van Yvonne",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 6,
          initials: "F.",
          first_name: "Henkie",
          last_name: "de Knip",
          locality: "Test Location",
        },
      ],
    },
  ],
};
