import type {
  ApportionmentState,
  CandidateNomination,
  CommitteeSession,
  ElectionSummary,
  ElectionWithPoliticalGroups,
  SeatAssignment,
} from "@/types/generated/openapi";

export const state: ApportionmentState = {
  type: "Finalised",
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [],
};

export const seat_assignment: SeatAssignment = {
  seats: 20,
  full_seats: 19,
  residual_seats: 1,
  quota: {
    integer: 400,
    numerator: 0,
    denominator: 20,
  },
  steps: [
    {
      change: {
        changed_by: "ListExhaustionRemoval",
        list_retracted_seat: 1,
        full_seat: true,
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 2000,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 333,
            numerator: 2,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 2000,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 333,
            numerator: 2,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 1600,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 320,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 4,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 1600,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 320,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 4,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 800,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 266,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 1,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_list_number: 2,
        list_options: [2],
        list_assigned: [2],
        list_exhausted: [1],
        votes_per_seat: {
          integer: 333,
          numerator: 2,
          denominator: 6,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 2000,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 400,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 4,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 2000,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 333,
            numerator: 2,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 1600,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 320,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 4,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 1600,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 320,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 4,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 800,
          remainder_votes: {
            integer: 0,
            numerator: 0,
            denominator: 20,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 266,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
      ],
    },
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 2000,
      remainder_votes: {
        integer: 0,
        numerator: 0,
        denominator: 20,
      },
      meets_remainder_threshold: true,
      full_seats: 4,
      residual_seats: 0,
      total_seats: 4,
    },
    {
      list_number: 2,
      votes_cast: 2000,
      remainder_votes: {
        integer: 0,
        numerator: 0,
        denominator: 20,
      },
      meets_remainder_threshold: true,
      full_seats: 5,
      residual_seats: 1,
      total_seats: 6,
    },
    {
      list_number: 3,
      votes_cast: 1600,
      remainder_votes: {
        integer: 0,
        numerator: 0,
        denominator: 20,
      },
      meets_remainder_threshold: true,
      full_seats: 4,
      residual_seats: 0,
      total_seats: 4,
    },
    {
      list_number: 4,
      votes_cast: 1600,
      remainder_votes: {
        integer: 0,
        numerator: 0,
        denominator: 20,
      },
      meets_remainder_threshold: true,
      full_seats: 4,
      residual_seats: 0,
      total_seats: 4,
    },
    {
      list_number: 5,
      votes_cast: 800,
      remainder_votes: {
        integer: 0,
        numerator: 0,
        denominator: 20,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
  ],
};

export const candidate_nomination: CandidateNomination = {
  preference_threshold: {
    percentage: 25,
    number_of_votes: {
      integer: 100,
      numerator: 0,
      denominator: 2000,
    },
  },
  chosen_candidates: [
    {
      number: 1,
      initials: "D.",
      first_name: "Dirk-Jan",
      last_name: "Arets",
      locality: "Hoek van Zoom",
      gender: "Male",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 2,
      initials: "T.A.",
      first_name: "Teun",
      last_name_prefix: "van",
      last_name: "Bekking",
      locality: "Middelgein",
      gender: "Male",
      list_number: 3,
      list_name: "Political Group C",
    },
    {
      number: 1,
      initials: "C.R.C.O.",
      first_name: "Cornelus",
      last_name: "Boermans",
      locality: "Heemdamseburg",
      gender: "Female",
      list_number: 1,
      list_name: "Political Group A",
    },
    {
      number: 2,
      initials: "J.R.",
      first_name: "Royce",
      last_name: "Brienen",
      locality: "Lekkum",
      gender: "Male",
      list_number: 1,
      list_name: "Political Group A",
    },
    {
      number: 5,
      initials: "F.U.",
      first_name: "Florien",
      last_name: "Cornelis",
      locality: "Sluisdam",
      gender: "X",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 1,
      initials: "V.R.",
      first_name: "Damian",
      last_name: "Cornelis",
      locality: "Juinen",
      gender: "Male",
      list_number: 3,
      list_name: "Political Group C",
    },
    {
      number: 4,
      initials: "E.",
      first_name: "Esra",
      last_name: "Groenen",
      locality: "Heemdamseburg",
      gender: "Male",
      list_number: 3,
      list_name: "Political Group C",
    },
    {
      number: 2,
      initials: "F.",
      first_name: "Florien",
      last_name: "Groenen",
      locality: "Bloemstede",
      gender: "Male",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 4,
      initials: "R.",
      first_name: "Rachid",
      last_name: "Groenen",
      locality: "Lekkum",
      gender: "Female",
      list_number: 4,
      list_name: "Political Group D",
    },
    {
      number: 3,
      initials: "L.C.F.",
      first_name: "Leontien",
      last_name: "Güneş",
      locality: "Hoek van Zoom",
      gender: "Male",
      list_number: 1,
      list_name: "Political Group A",
    },
    {
      number: 2,
      initials: "U.",
      first_name: "Nicolaas",
      last_name: "Hoogstraten",
      locality: "Heemdamseburg",
      gender: "Male",
      list_number: 4,
      list_name: "Political Group D",
    },
    {
      number: 4,
      initials: "E.L.A.",
      first_name: "Edis",
      last_name: "Katsma",
      locality: "Middelgein",
      gender: "Male",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 1,
      initials: "E.N.",
      first_name: "Esra",
      last_name: "Katsma",
      locality: "Huisden",
      gender: "Male",
      list_number: 5,
      list_name: "Political Group E",
    },
    {
      number: 6,
      initials: "H.K.",
      first_name: "Henk",
      last_name_prefix: "van der",
      last_name: "Spek",
      locality: "Eemstricht",
      gender: "X",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 1,
      initials: "C.F.",
      first_name: "Cornelus",
      last_name: "Tax",
      locality: "Bloemstede",
      gender: "Male",
      list_number: 4,
      list_name: "Political Group D",
    },
    {
      number: 3,
      initials: "S.K.F.",
      first_name: "Sibel",
      last_name: "Tax",
      locality: "Hoek van Zoom",
      gender: "Male",
      list_number: 2,
      list_name: "Political Group B",
    },
    {
      number: 4,
      initials: "S.",
      first_name: "Salomon",
      last_name: "Titulaer",
      locality: "Juinen",
      gender: "X",
      list_number: 1,
      list_name: "Political Group A",
    },
    {
      number: 3,
      initials: "C.",
      first_name: "Christina",
      last_name_prefix: "de",
      last_name: "Vegt",
      locality: "'s Gravenveen",
      gender: "Female",
      list_number: 4,
      list_name: "Political Group D",
    },
    {
      number: 3,
      initials: "R.",
      first_name: "Ruth",
      last_name_prefix: "van de",
      last_name: "Wal",
      locality: "Bloemstede",
      gender: "Female",
      list_number: 3,
      list_name: "Political Group C",
    },
    {
      number: 2,
      initials: "Y.",
      first_name: "Yağmur",
      last_name: "Wiertz",
      locality: "Lekkum",
      gender: "X",
      list_number: 5,
      list_name: "Political Group E",
    },
  ],
  list_candidate_nomination: [
    {
      list_number: 1,
      list_name: "Political Group A",
      list_seats: 4,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 2,
          votes: 500,
        },
        {
          number: 3,
          votes: 500,
        },
        {
          number: 4,
          votes: 500,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 2,
      list_name: "Political Group B",
      list_seats: 6,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
        {
          number: 5,
          votes: 400,
        },
      ],
      other_candidate_nomination: [
        {
          number: 6,
          votes: 0,
        },
      ],
      updated_candidate_ranking: [],
    },
    {
      list_number: 3,
      list_name: "Political Group C",
      list_seats: 4,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 4,
      list_name: "Political Group D",
      list_seats: 4,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 5,
      list_name: "Political Group E",
      list_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 8000,
    proxy_certificate_count: 0,
    total_admitted_voters_count: 8000,
  },
  votes_counts: {
    political_group_total_votes: [
      {
        number: 1,
        total: 2000,
      },
      {
        number: 2,
        total: 2000,
      },
      {
        number: 3,
        total: 1600,
      },
      {
        number: 4,
        total: 1600,
      },
      {
        number: 5,
        total: 800,
      },
    ],
    total_votes_candidates_count: 8000,
    blank_votes_count: 0,
    invalid_votes_count: 0,
    total_votes_cast_count: 8000,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
    fewer_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
  },
  political_group_votes: [
    {
      number: 1,
      total: 2000,
      candidate_votes: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 2,
          votes: 500,
        },
        {
          number: 3,
          votes: 500,
        },
        {
          number: 4,
          votes: 500,
        },
      ],
    },
    {
      number: 2,
      total: 2000,
      candidate_votes: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
        {
          number: 5,
          votes: 400,
        },
        {
          number: 6,
          votes: 0,
        },
      ],
    },
    {
      number: 3,
      total: 1600,
      candidate_votes: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
        {
          number: 5,
          votes: 0,
        },
      ],
    },
    {
      number: 4,
      total: 1600,
      candidate_votes: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 400,
        },
        {
          number: 5,
          votes: 0,
        },
      ],
    },
    {
      number: 5,
      total: 800,
      candidate_votes: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 400,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
      ],
    },
  ],
  polling_station_investigations: {
    admitted_voters_recounted: [],
    investigated_other_reason: [],
    ballots_recounted: [],
  },
  number_of_voters: 8634,
};

export const committee_session: CommitteeSession = {
  id: 1,
  number: 1,
  election_id: 5,
  status: "completed",
  location: "",
  start_date_time: "",
};

export const election: ElectionWithPoliticalGroups = {
  id: 2,
  name: "Election >= 19 seats with full seat removal",
  committee_category: "CSB",
  election_id: "GR2026_Juinen",
  location: "Juinen",
  domain_id: "0035",
  category: "Municipal",
  number_of_seats: 20,
  number_of_voters: 1,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  political_groups: [
    {
      number: 1,
      name: "Political Group A",
      candidates: [
        {
          number: 1,
          initials: "C.R.C.O.",
          first_name: "Cornelus",
          last_name: "Boermans",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 2,
          initials: "J.R.",
          first_name: "Royce",
          last_name: "Brienen",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 3,
          initials: "L.C.F.",
          first_name: "Leontien",
          last_name: "Güneş",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Salomon",
          last_name: "Titulaer",
          locality: "Juinen",
          gender: "X",
        },
      ],
    },
    {
      number: 2,
      name: "Political Group B",
      candidates: [
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name: "Arets",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 2,
          initials: "F.",
          first_name: "Florien",
          last_name: "Groenen",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 3,
          initials: "S.K.F.",
          first_name: "Sibel",
          last_name: "Tax",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 4,
          initials: "E.L.A.",
          first_name: "Edis",
          last_name: "Katsma",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 5,
          initials: "F.U.",
          first_name: "Florien",
          last_name: "Cornelis",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 6,
          initials: "H.K.",
          first_name: "Henk",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Eemstricht",
          gender: "X",
        },
      ],
    },
    {
      number: 3,
      name: "Political Group C",
      candidates: [
        {
          number: 1,
          initials: "V.R.",
          first_name: "Damian",
          last_name: "Cornelis",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.A.",
          first_name: "Teun",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 3,
          initials: "R.",
          first_name: "Ruth",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 4,
          initials: "E.",
          first_name: "Esra",
          last_name: "Groenen",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 5,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Arets",
          locality: "Hovenerwoud",
          gender: "Female",
        },
      ],
    },
    {
      number: 4,
      name: "Political Group D",
      candidates: [
        {
          number: 1,
          initials: "C.F.",
          first_name: "Cornelus",
          last_name: "Tax",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 2,
          initials: "U.",
          first_name: "Nicolaas",
          last_name: "Hoogstraten",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 3,
          initials: "C.",
          first_name: "Christina",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 4,
          initials: "R.",
          first_name: "Rachid",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 5,
          initials: "M.Z.X.",
          first_name: "Madelène",
          last_name: "Hoogstraten",
          locality: "Heemdamseburg",
          gender: "X",
        },
      ],
    },
    {
      number: 5,
      name: "Political Group E",
      candidates: [
        {
          number: 1,
          initials: "E.N.",
          first_name: "Esra",
          last_name: "Katsma",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 2,
          initials: "Y.",
          first_name: "Yağmur",
          last_name: "Wiertz",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 3,
          initials: "L.V.",
          first_name: "Leontien",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 4,
          initials: "G.Z.",
          first_name: "Gijsbertje",
          last_name: "Katsma",
          locality: "Eemstricht",
          gender: "X",
        },
      ],
    },
  ],
};
