import { CandidateNominationResult, Election, ElectionSummary, SeatAssignmentResult } from "@/api/gen/openapi";

export const seat_assignment: SeatAssignmentResult = {
  seats: 24,
  full_seats: 18,
  residual_seats: 6,
  quota: {
    integer: 625,
    numerator: 1,
    denominator: 24,
  },
  steps: [
    {
      residual_seat_number: 1,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 2,
        pg_options: [2, 3, 4, 5, 6],
        pg_assigned: [2],
        votes_per_seat: {
          integer: 624,
          numerator: 1,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 2,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 3,
        pg_options: [3, 4, 5, 6],
        pg_assigned: [2, 3],
        votes_per_seat: {
          integer: 624,
          numerator: 1,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 3,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 4,
        pg_options: [4, 5, 6],
        pg_assigned: [2, 3, 4],
        votes_per_seat: {
          integer: 624,
          numerator: 1,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 4,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 5,
        pg_options: [5, 6],
        pg_assigned: [2, 3, 4, 5],
        votes_per_seat: {
          integer: 624,
          numerator: 1,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 5,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 6,
        pg_options: [6],
        pg_assigned: [2, 3, 4, 5, 6],
        votes_per_seat: {
          integer: 624,
          numerator: 1,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 6,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_pg_number: 7,
        pg_options: [7],
        pg_assigned: [7],
        votes_per_seat: {
          integer: 624,
          numerator: 0,
          denominator: 2,
        },
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 0,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 624,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      change: {
        changed_by: "AbsoluteMajorityReassignment",
        pg_retracted_seat: 7,
        pg_assigned_seat: 1,
      },
      standings: [
        {
          pg_number: 1,
          votes_cast: 7501,
          remainder_votes: {
            integer: 0,
            numerator: 12,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 577,
            numerator: 0,
            denominator: 13,
          },
          full_seats: 12,
          residual_seats: 1,
        },
        {
          pg_number: 2,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 3,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 4,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 5,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 6,
          votes_cast: 1249,
          remainder_votes: {
            integer: 623,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 1,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 1,
        },
        {
          pg_number: 7,
          votes_cast: 1248,
          remainder_votes: {
            integer: 622,
            numerator: 23,
            denominator: 24,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 416,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 1,
          residual_seats: 0,
        },
        {
          pg_number: 8,
          votes_cast: 7,
          remainder_votes: {
            integer: 7,
            numerator: 0,
            denominator: 24,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 7,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
  ],
  final_standing: [
    {
      pg_number: 1,
      votes_cast: 7501,
      remainder_votes: {
        integer: 0,
        numerator: 12,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 12,
      residual_seats: 1,
      total_seats: 13,
    },
    {
      pg_number: 2,
      votes_cast: 1249,
      remainder_votes: {
        integer: 623,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 3,
      votes_cast: 1249,
      remainder_votes: {
        integer: 623,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 4,
      votes_cast: 1249,
      remainder_votes: {
        integer: 623,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 5,
      votes_cast: 1249,
      remainder_votes: {
        integer: 623,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 6,
      votes_cast: 1249,
      remainder_votes: {
        integer: 623,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 1,
      total_seats: 2,
    },
    {
      pg_number: 7,
      votes_cast: 1248,
      remainder_votes: {
        integer: 622,
        numerator: 23,
        denominator: 24,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 0,
      total_seats: 1,
    },
    {
      pg_number: 8,
      votes_cast: 7,
      remainder_votes: {
        integer: 7,
        numerator: 0,
        denominator: 24,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
  ],
};

export const candidate_nomination: CandidateNominationResult = {
  preference_threshold: {
    percentage: 25,
    number_of_votes: {
      integer: 156,
      numerator: 625,
      denominator: 2400,
    },
  },
  chosen_candidates: [
    {
      number: 8,
      initials: "S.",
      first_name: "Sophie",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "T.",
      first_name: "Tinus",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 10,
      initials: "M.",
      first_name: "Marijke",
      last_name_prefix: "van den",
      last_name: "Berg",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "T.J.",
      first_name: "Tedje Johannes",
      last_name_prefix: "van",
      last_name: "Es",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 1,
      initials: "T.",
      first_name: "Tjolk",
      last_name: "Hekking",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 2,
      initials: "H.",
      first_name: "Henny",
      last_name: "Hekking",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "T.",
      first_name: "Tom",
      last_name: "Hekking",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 1,
      initials: "F.",
      first_name: "Frederik",
      last_name: "Jacobse",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 4,
      initials: "A.",
      first_name: "Arie",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 2,
      initials: "P.",
      first_name: "Piet",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 4,
      initials: "T.J.",
      first_name: "Tessa",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 11,
      initials: "R.",
      first_name: "Rolf",
      last_name_prefix: "de",
      last_name: "Jong",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 12,
      initials: "K.",
      first_name: "Karin",
      last_name: "Kok",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "E.",
      first_name: "Eva",
      last_name: "Koster",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "L.",
      first_name: "Lidewij",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "J.",
      first_name: "Johan",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 3,
      initials: "M.",
      first_name: "Marijke",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 7,
      initials: "K.",
      first_name: "Klaas",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 2,
      initials: "D.",
      last_name: "Po",
      locality: "Test Location",
      gender: "X",
    },
    {
      number: 13,
      initials: "G.",
      first_name: "Gert",
      last_name: "Smit",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 1,
      initials: "G.",
      first_name: "Gert",
      last_name: "Smit",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 9,
      initials: "J.",
      first_name: "Johan",
      last_name_prefix: "de",
      last_name: "Vries",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 5,
      initials: "H.",
      first_name: "Henk",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 6,
      initials: "B.",
      first_name: "Berta",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Female",
    },
  ],
  political_group_candidate_nomination: [
    {
      pg_number: 1,
      pg_name: "Political Group A",
      pg_seats: 13,
      preferential_candidate_nomination: [
        {
          number: 11,
          votes: 1200,
        },
        {
          number: 1,
          votes: 1069,
        },
        {
          number: 13,
          votes: 1000,
        },
        {
          number: 12,
          votes: 720,
        },
        {
          number: 6,
          votes: 500,
        },
        {
          number: 8,
          votes: 425,
        },
        {
          number: 3,
          votes: 421,
        },
        {
          number: 2,
          votes: 403,
        },
        {
          number: 7,
          votes: 400,
        },
        {
          number: 10,
          votes: 370,
        },
        {
          number: 5,
          votes: 368,
        },
        {
          number: 9,
          votes: 315,
        },
        {
          number: 4,
          votes: 310,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 11,
          initials: "R.",
          first_name: "Rolf",
          last_name_prefix: "de",
          last_name: "Jong",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 1,
          initials: "L.",
          first_name: "Lidewij",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 13,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 12,
          initials: "K.",
          first_name: "Karin",
          last_name: "Kok",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Berta",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 8,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "M.",
          first_name: "Marijke",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Johan",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 7,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "M.",
          first_name: "Marijke",
          last_name_prefix: "van den",
          last_name: "Berg",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 9,
          initials: "J.",
          first_name: "Johan",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "A.",
          first_name: "Arie",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      pg_number: 2,
      pg_name: "Political Group B",
      pg_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 552,
        },
        {
          number: 2,
          votes: 307,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tinus",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "D.",
          last_name: "Po",
          locality: "Test Location",
          gender: "X",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Kloosterboer",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Willem",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      pg_number: 3,
      pg_name: "Political Group C",
      pg_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 1000,
        },
        {
          number: 2,
          votes: 249,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 4,
      pg_name: "Political Group D",
      pg_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 800,
        },
        {
          number: 2,
          votes: 449,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 5,
      pg_name: "Political Group E",
      pg_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 949,
        },
        {
          number: 2,
          votes: 300,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 6,
      pg_name: "Political Group F",
      pg_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 4,
          votes: 403,
        },
        {
          number: 2,
          votes: 300,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 4,
          initials: "T.J.",
          first_name: "Tessa",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "P.",
          first_name: "Piet",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "A.",
          first_name: "Annelies",
          last_name_prefix: "van",
          last_name: "Loon",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      pg_number: 7,
      pg_name: "Political Group G",
      pg_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 500,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.H.",
          first_name: "Tjolkse Hendrika",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Hans",
          last_name_prefix: "van der",
          last_name: "Vaart",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      pg_number: 8,
      pg_name: "Political Group H",
      pg_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 15001,
    proxy_certificate_count: 1,
    voter_card_count: 0,
    total_admitted_voters_count: 15002,
  },
  votes_counts: {
    votes_candidates_count: 15001,
    blank_votes_count: 0,
    invalid_votes_count: 1,
    total_votes_cast_count: 15002,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    fewer_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    unreturned_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    too_few_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    too_many_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    other_explanation_count: {
      count: 0,
      polling_stations: [],
    },
    no_explanation_count: {
      count: 0,
      polling_stations: [],
    },
  },
  recounted_polling_stations: [],
  political_group_votes: [
    {
      number: 1,
      total: 7501,
      candidate_votes: [
        {
          number: 1,
          votes: 1069,
        },
        {
          number: 2,
          votes: 403,
        },
        {
          number: 3,
          votes: 421,
        },
        {
          number: 4,
          votes: 310,
        },
        {
          number: 5,
          votes: 368,
        },
        {
          number: 6,
          votes: 500,
        },
        {
          number: 7,
          votes: 400,
        },
        {
          number: 8,
          votes: 425,
        },
        {
          number: 9,
          votes: 315,
        },
        {
          number: 10,
          votes: 370,
        },
        {
          number: 11,
          votes: 1200,
        },
        {
          number: 12,
          votes: 720,
        },
        {
          number: 13,
          votes: 1000,
        },
      ],
    },
    {
      number: 2,
      total: 1249,
      candidate_votes: [
        {
          number: 1,
          votes: 552,
        },
        {
          number: 2,
          votes: 307,
        },
        {
          number: 3,
          votes: 180,
        },
        {
          number: 4,
          votes: 210,
        },
      ],
    },
    {
      number: 3,
      total: 1249,
      candidate_votes: [
        {
          number: 1,
          votes: 1000,
        },
        {
          number: 2,
          votes: 249,
        },
      ],
    },
    {
      number: 4,
      total: 1249,
      candidate_votes: [
        {
          number: 1,
          votes: 800,
        },
        {
          number: 2,
          votes: 449,
        },
      ],
    },
    {
      number: 5,
      total: 1249,
      candidate_votes: [
        {
          number: 1,
          votes: 949,
        },
        {
          number: 2,
          votes: 300,
        },
      ],
    },
    {
      number: 6,
      total: 1249,
      candidate_votes: [
        {
          number: 1,
          votes: 266,
        },
        {
          number: 2,
          votes: 300,
        },
        {
          number: 3,
          votes: 280,
        },
        {
          number: 4,
          votes: 403,
        },
      ],
    },
    {
      number: 7,
      total: 1248,
      candidate_votes: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 2,
          votes: 248,
        },
        {
          number: 3,
          votes: 200,
        },
        {
          number: 4,
          votes: 300,
        },
      ],
    },
    {
      number: 8,
      total: 7,
      candidate_votes: [
        {
          number: 1,
          votes: 5,
        },
        {
          number: 2,
          votes: 1,
        },
        {
          number: 3,
          votes: 1,
        },
      ],
    },
  ],
};

export const election: Election = {
  id: 5,
  name: "Test Election >= 19 seats & Absolute Majority Change",
  location: "Test Location",
  number_of_voters: 20000,
  category: "Municipal",
  number_of_seats: 24,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  status: "DataEntryFinished",
  political_groups: [
    {
      number: 1,
      name: "Political Group A",
      candidates: [
        {
          number: 1,
          initials: "L.",
          first_name: "Lidewij",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Johan",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "M.",
          first_name: "Marijke",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "A.",
          first_name: "Arie",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Berta",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 7,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 8,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 9,
          initials: "J.",
          first_name: "Johan",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "M.",
          first_name: "Marijke",
          last_name_prefix: "van den",
          last_name: "Berg",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 11,
          initials: "R.",
          first_name: "Rolf",
          last_name_prefix: "de",
          last_name: "Jong",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 12,
          initials: "K.",
          first_name: "Karin",
          last_name: "Kok",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 13,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 2,
      name: "Political Group B",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tinus",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "D.",
          last_name: "Po",
          locality: "Test Location",
          gender: "X",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Willem",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Kloosterboer",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 3,
      name: "Political Group C",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Eva",
          last_name: "Koster",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 4,
      name: "Political Group D",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 5,
      name: "Political Group E",
      candidates: [
        {
          number: 1,
          initials: "F.",
          first_name: "Frederik",
          last_name: "Jacobse",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.J.",
          first_name: "Tedje Johannes",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 6,
      name: "Political Group F",
      candidates: [
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "P.",
          first_name: "Piet",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "A.",
          first_name: "Annelies",
          last_name_prefix: "van",
          last_name: "Loon",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "T.J.",
          first_name: "Tessa",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 7,
      name: "Political Group G",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Hans",
          last_name_prefix: "van der",
          last_name: "Vaart",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.H.",
          first_name: "Tjolkse Hendrika",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 8,
      name: "Political Group H",
      candidates: [
        {
          number: 1,
          initials: "F.",
          first_name: "Frederik",
          last_name: "Jacobse",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.J.",
          first_name: "Tedje Johannes",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "K.",
          first_name: "Karel",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
  ],
};
