import type {
  ApportionmentState,
  CommitteeSession,
  ElectionSummary,
  ElectionWithPoliticalGroups,
  HighestAverageResidualSeatDrawingLots,
  SeatAssignment,
} from "@/types/generated/openapi";

export const options = [2, 3, 4, 5, 6];
export const drawing_lots_required: HighestAverageResidualSeatDrawingLots & {
  variant: "HighestAverageResidualSeat";
} = {
  variant: "HighestAverageResidualSeat",
  max_average: {
    integer: 46,
    numerator: 2,
    denominator: 3,
  },
  residual_seat_numbers: [2, 3, 4],
  options,
  list_averages: [
    {
      pg_number: 1,
      average: {
        integer: 45,
        numerator: 5,
        denominator: 11,
      },
    },
    {
      pg_number: 2,
      average: {
        integer: 46,
        numerator: 2,
        denominator: 3,
      },
    },
    {
      pg_number: 3,
      average: {
        integer: 46,
        numerator: 2,
        denominator: 3,
      },
    },
    {
      pg_number: 4,
      average: {
        integer: 46,
        numerator: 2,
        denominator: 3,
      },
    },
    {
      pg_number: 5,
      average: {
        integer: 46,
        numerator: 2,
        denominator: 3,
      },
    },
    {
      pg_number: 6,
      average: {
        integer: 46,
        numerator: 2,
        denominator: 3,
      },
    },
  ],
};

export const state: ApportionmentState = {
  type: "DrawingLots",
  drawing_lots_required: {
    type: "ListDrawingLotsRequired",
    ...drawing_lots_required,
  },
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [],
};

export const state_after_one_drawing_lots_seat_assigned: ApportionmentState = {
  type: "DrawingLots",
  drawing_lots_required: {
    type: "ListDrawingLotsRequired",
    variant: "HighestAverageResidualSeat",
    max_average: {
      integer: 46,
      numerator: 2,
      denominator: 3,
    },
    residual_seat_numbers: [3, 4],
    options: [2, 3, 5, 6],
    list_averages: [
      {
        pg_number: 1,
        average: {
          integer: 45,
          numerator: 5,
          denominator: 11,
        },
      },
      {
        pg_number: 2,
        average: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
      },
      {
        pg_number: 3,
        average: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
      },
      {
        pg_number: 4,
        average: {
          integer: 35,
          numerator: 0,
          denominator: 4,
        },
      },
      {
        pg_number: 5,
        average: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
      },
      {
        pg_number: 6,
        average: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
      },
    ],
  },
  deceased_candidates: [],
  lists_drawn: [
    {
      variant: {
        variant: "HighestAverageResidualSeat",
        max_average: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
        residual_seat_numbers: [2, 3, 4],
        options: [2, 3, 4, 5, 6],
        list_averages: [
          {
            pg_number: 1,
            average: {
              integer: 45,
              numerator: 5,
              denominator: 11,
            },
          },
          {
            pg_number: 2,
            average: {
              integer: 46,
              numerator: 2,
              denominator: 3,
            },
          },
          {
            pg_number: 3,
            average: {
              integer: 46,
              numerator: 2,
              denominator: 3,
            },
          },
          {
            pg_number: 4,
            average: {
              integer: 46,
              numerator: 2,
              denominator: 3,
            },
          },
          {
            pg_number: 5,
            average: {
              integer: 46,
              numerator: 2,
              denominator: 3,
            },
          },
          {
            pg_number: 6,
            average: {
              integer: 46,
              numerator: 2,
              denominator: 3,
            },
          },
        ],
      },
      drawn: 4,
    },
  ],
  candidates_drawn: [],
};

export const seat_assignment: SeatAssignment = {
  seats: 23,
  full_seats: 19,
  residual_seats: 4,
  quota: {
    integer: 52,
    numerator: 4,
    denominator: 23,
  },
  steps: [
    {
      residual_seat_number: 1,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_list_number: 1,
        list_options: [1],
        list_assigned: [1],
        list_exhausted: [],
        votes_per_seat: {
          integer: 50,
          numerator: 0,
          denominator: 10,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 500,
          remainder_votes: {
            integer: 30,
            numerator: 10,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 50,
            numerator: 0,
            denominator: 10,
          },
          full_seats: 9,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
      ],
    },
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 500,
      remainder_votes: {
        integer: 30,
        numerator: 10,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 9,
      residual_seats: 1,
      total_seats: 10,
    },
    {
      list_number: 2,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 3,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 4,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 5,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 6,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
  ],
};

export const seat_assignment_after_one_drawing_lots_seat_assigned: SeatAssignment = {
  ...seat_assignment,
  steps: [
    ...seat_assignment.steps,
    {
      residual_seat_number: 2,
      change: {
        changed_by: "HighestAverageAssignment",
        selected_list_number: 4,
        list_options: [2, 3, 4, 5, 6],
        list_assigned: [4],
        list_exhausted: [],
        votes_per_seat: {
          integer: 46,
          numerator: 2,
          denominator: 3,
        },
        drawing_lots: {
          variant: "HighestAverageResidualSeat",
          max_average: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          residual_seat_numbers: [2, 3, 4],
          options: [2, 3, 4, 5, 6],
          list_averages: [
            {
              pg_number: 1,
              average: {
                integer: 45,
                numerator: 5,
                denominator: 11,
              },
            },
            {
              pg_number: 2,
              average: {
                integer: 46,
                numerator: 2,
                denominator: 3,
              },
            },
            {
              pg_number: 3,
              average: {
                integer: 46,
                numerator: 2,
                denominator: 3,
              },
            },
            {
              pg_number: 4,
              average: {
                integer: 46,
                numerator: 2,
                denominator: 3,
              },
            },
            {
              pg_number: 5,
              average: {
                integer: 46,
                numerator: 2,
                denominator: 3,
              },
            },
            {
              pg_number: 6,
              average: {
                integer: 46,
                numerator: 2,
                denominator: 3,
              },
            },
          ],
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 500,
          remainder_votes: {
            integer: 30,
            numerator: 10,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 45,
            numerator: 5,
            denominator: 11,
          },
          full_seats: 9,
          residual_seats: 1,
        },
        {
          list_number: 2,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 140,
          remainder_votes: {
            integer: 35,
            numerator: 15,
            denominator: 23,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 46,
            numerator: 2,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
      ],
    },
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 500,
      remainder_votes: {
        integer: 30,
        numerator: 10,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 9,
      residual_seats: 1,
      total_seats: 10,
    },
    {
      list_number: 2,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 3,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 4,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 1,
      total_seats: 3,
    },
    {
      list_number: 5,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 6,
      votes_cast: 140,
      remainder_votes: {
        integer: 35,
        numerator: 15,
        denominator: 23,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
  ],
};

export const election_summary: ElectionSummary = {
  number_of_voters: 1329,
  voters_counts: {
    poll_card_count: 1200,
    proxy_certificate_count: 0,
    total_admitted_voters_count: 1200,
  },
  votes_counts: {
    political_group_total_votes: [
      {
        number: 1,
        total: 500,
      },
      {
        number: 2,
        total: 140,
      },
      {
        number: 3,
        total: 140,
      },
      {
        number: 4,
        total: 140,
      },
      {
        number: 5,
        total: 140,
      },
      {
        number: 6,
        total: 140,
      },
    ],
    total_votes_candidates_count: 1200,
    blank_votes_count: 0,
    invalid_votes_count: 0,
    total_votes_cast_count: 1200,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
    fewer_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
  },
  political_group_votes: [
    {
      number: 1,
      total: 500,
      candidate_votes: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
    {
      number: 2,
      total: 140,
      candidate_votes: [
        {
          number: 1,
          votes: 140,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
    {
      number: 3,
      total: 140,
      candidate_votes: [
        {
          number: 1,
          votes: 140,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
    {
      number: 4,
      total: 140,
      candidate_votes: [
        {
          number: 1,
          votes: 140,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
    {
      number: 5,
      total: 140,
      candidate_votes: [
        {
          number: 1,
          votes: 140,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
    {
      number: 6,
      total: 140,
      candidate_votes: [
        {
          number: 1,
          votes: 140,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
        {
          number: 11,
          votes: 0,
        },
        {
          number: 12,
          votes: 0,
        },
        {
          number: 13,
          votes: 0,
        },
        {
          number: 14,
          votes: 0,
        },
        {
          number: 15,
          votes: 0,
        },
        {
          number: 16,
          votes: 0,
        },
        {
          number: 17,
          votes: 0,
        },
        {
          number: 18,
          votes: 0,
        },
        {
          number: 19,
          votes: 0,
        },
        {
          number: 20,
          votes: 0,
        },
        {
          number: 21,
          votes: 0,
        },
        {
          number: 22,
          votes: 0,
        },
        {
          number: 23,
          votes: 0,
        },
        {
          number: 24,
          votes: 0,
        },
        {
          number: 25,
          votes: 0,
        },
        {
          number: 26,
          votes: 0,
        },
        {
          number: 27,
          votes: 0,
        },
        {
          number: 28,
          votes: 0,
        },
        {
          number: 29,
          votes: 0,
        },
        {
          number: 30,
          votes: 0,
        },
        {
          number: 31,
          votes: 0,
        },
        {
          number: 32,
          votes: 0,
        },
        {
          number: 33,
          votes: 0,
        },
        {
          number: 34,
          votes: 0,
        },
        {
          number: 35,
          votes: 0,
        },
        {
          number: 36,
          votes: 0,
        },
        {
          number: 37,
          votes: 0,
        },
        {
          number: 38,
          votes: 0,
        },
        {
          number: 39,
          votes: 0,
        },
        {
          number: 40,
          votes: 0,
        },
        {
          number: 41,
          votes: 0,
        },
        {
          number: 42,
          votes: 0,
        },
        {
          number: 43,
          votes: 0,
        },
        {
          number: 44,
          votes: 0,
        },
        {
          number: 45,
          votes: 0,
        },
        {
          number: 46,
          votes: 0,
        },
        {
          number: 47,
          votes: 0,
        },
        {
          number: 48,
          votes: 0,
        },
        {
          number: 49,
          votes: 0,
        },
        {
          number: 50,
          votes: 0,
        },
      ],
    },
  ],
  polling_station_investigations: {
    admitted_voters_recounted: [],
    investigated_other_reason: [],
    ballots_recounted: [],
  },
};

export const committee_session: CommitteeSession = {
  id: 8,
  number: 1,
  election_id: 8,
  status: "completed",
  location: "",
  start_date_time: "",
};

export const election: ElectionWithPoliticalGroups = {
  id: 8,
  name: "Drawing lots >= 19 seats, HighestAverageResidualSeat",
  committee_category: "CSB",
  election_id: "GR2026_Juinen",
  location: "Juinen",
  domain_id: "0035",
  category: "Municipal",
  number_of_seats: 23,
  number_of_voters: 1,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  political_groups: [
    {
      number: 1,
      name: "Partij voor de Stemmer",
      candidates: [
        {
          number: 1,
          initials: "E.Y.",
          first_name: "Edis",
          last_name: "Arets",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 2,
          initials: "K.X.",
          first_name: "Kris",
          last_name: "Boermans",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 3,
          initials: "S.",
          first_name: "Sibel",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 4,
          initials: "Y.",
          first_name: "Silvana",
          last_name: "Boermans",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 5,
          initials: "J.Q.",
          first_name: "Jelisa",
          last_name: "Groenen",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 6,
          initials: "L.",
          first_name: "Leontien",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 7,
          initials: "K.C.D.",
          first_name: "Kris",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 8,
          initials: "F.V.",
          first_name: "Florien",
          last_name: "Arets",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 9,
          initials: "S.X.",
          first_name: "Sammie",
          last_name: "Oorschot",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 10,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Philippen",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 11,
          initials: "L.U.A.",
          first_name: "Leontien",
          last_name: "Tax",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 12,
          initials: "Y.N.",
          first_name: "Yağmur",
          last_name: "Aygün",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 13,
          initials: "N.",
          first_name: "Nikky",
          last_name: "Goedhart",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 14,
          initials: "E.H.F.",
          first_name: "Edis",
          last_name: "Wiertz",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 15,
          initials: "İ.",
          first_name: "İlknur",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 16,
          initials: "S.N.G.Z.E.",
          first_name: "Sijtze",
          last_name: "Titulaer",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 17,
          initials: "S.X.",
          first_name: "Sijtze",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 18,
          initials: "Y.A.",
          first_name: "Yağmur",
          last_name: "Titulaer",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 19,
          initials: "H.H.",
          first_name: "Henk",
          last_name: "Oorschot",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 20,
          initials: "R.N.U.",
          first_name: "Renso",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 21,
          initials: "R.",
          first_name: "Renso",
          last_name: "Oorschot",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 22,
          initials: "J.L.",
          first_name: "Jelisa",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 23,
          initials: "J.G.K.",
          first_name: "Jelisa",
          last_name: "Aygün",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 24,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Wiertz",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 25,
          initials: "H.",
          first_name: "Henk",
          last_name: "Boermans",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 26,
          initials: "B.M.",
          first_name: "İlknur",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 27,
          initials: "E.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 28,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name: "Tax",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 29,
          initials: "G.F.R.F.",
          first_name: "Gijsbertje",
          last_name: "Arets",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 30,
          initials: "E.",
          first_name: "Eelko",
          last_name: "Goedhart",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 31,
          initials: "İ.",
          first_name: "İlknur",
          last_name: "Brienen",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 32,
          initials: "C.",
          first_name: "Cornelus",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 33,
          initials: "S.",
          first_name: "Silvana",
          last_name: "Meulenkolk",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 34,
          initials: "H.C.",
          first_name: "Henk",
          last_name: "Katsma",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 35,
          initials: "W.C.Z.",
          first_name: "Tiemen",
          last_name: "Arets",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 36,
          initials: "N.K.K.",
          first_name: "Tiemen",
          last_name: "Gopal",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 37,
          initials: "D.M.",
          first_name: "Damian",
          last_name: "Meulenkolk",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 38,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Gopal",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 39,
          initials: "İ.Z.",
          first_name: "İlknur",
          last_name: "Wolfswinkel",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 40,
          initials: "S.S.W.",
          first_name: "Salomon",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 41,
          initials: "M.T.",
          first_name: "Madelène",
          last_name: "Goedhart",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 42,
          initials: "E.",
          first_name: "Edis",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 43,
          initials: "J.",
          first_name: "Jory",
          last_name: "Brienen",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 44,
          initials: "S.X.",
          first_name: "Silvana",
          last_name: "Groenen",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 45,
          initials: "D.D.L.",
          first_name: "Damian",
          last_name: "Wiertz",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 46,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 47,
          initials: "S.C.",
          first_name: "Silvana",
          last_name: "Hoogstraten",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 48,
          initials: "K.F.T.",
          first_name: "Kris",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 49,
          initials: "S.T.I.",
          first_name: "Sijtze",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 50,
          initials: "T.",
          first_name: "Jelisa",
          last_name: "Philippen",
          locality: "Lekkum",
          gender: "X",
        },
      ],
    },
    {
      number: 2,
      name: "Algemene Partij",
      candidates: [
        {
          number: 1,
          initials: "N.",
          last_name: "Gopal",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 2,
          initials: "X.H.",
          last_name: "Aygün",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 3,
          initials: "J.",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 4,
          initials: "S.U.I.",
          last_name: "Bruins-Van den Kerk",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 5,
          initials: "V.",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 6,
          initials: "R.",
          last_name: "Goedhart",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 7,
          initials: "E.",
          last_name: "Goedhart",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 8,
          initials: "E.O.X.",
          last_name: "Wolfswinkel",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 9,
          initials: "Y.",
          last_name: "Tax",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 10,
          initials: "L.R.",
          last_name: "Born",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 11,
          initials: "D.A.",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 12,
          initials: "K.S.",
          last_name: "Aygün",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 13,
          initials: "K.M.G.",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 14,
          initials: "L.R.R.",
          last_name: "Prakken",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 15,
          initials: "S.",
          last_name: "Aygün",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 16,
          initials: "I.",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 17,
          initials: "G.S.J.B.",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 18,
          initials: "C.",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 19,
          initials: "D.",
          last_name: "Hoogstraten",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 20,
          initials: "P.",
          last_name: "Brienen",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 21,
          initials: "T.X.",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 22,
          initials: "E.",
          last_name: "Güneş",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 23,
          initials: "U.A.",
          last_name: "Philippen",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 24,
          initials: "L.",
          last_name: "Wiertz",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 25,
          initials: "X.J.",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 26,
          initials: "H.M.",
          last_name: "Titulaer",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 27,
          initials: "M.",
          last_name: "Born",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 28,
          initials: "Y.",
          last_name: "Boermans",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 29,
          initials: "J.",
          last_name: "Arets",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 30,
          initials: "E.S.",
          last_name: "Katsma",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 31,
          initials: "V.",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 32,
          initials: "J.",
          last_name: "Goedhart",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 33,
          initials: "T.S.",
          last_name: "Wolfswinkel",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 34,
          initials: "W.",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 35,
          initials: "E.B.R.",
          last_name: "Wiertz",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 36,
          initials: "Q.",
          last_name: "Goedhart",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 37,
          initials: "V.",
          last_name: "Aygün",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 38,
          initials: "X.",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 39,
          initials: "N.",
          last_name: "Bruins-Van den Kerk",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 40,
          initials: "R.H.",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 41,
          initials: "U.E.",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 42,
          initials: "U.",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 43,
          initials: "Z.T.",
          last_name: "Oorschot",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 44,
          initials: "K.",
          last_name: "Hoogstraten",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 45,
          initials: "F.B.",
          last_name: "Prakken",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 46,
          initials: "W.P.Z.",
          last_name: "Gopal",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 47,
          initials: "F.",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 48,
          initials: "S.C.Y.",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 49,
          initials: "S.W.",
          last_name: "Katsma",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 50,
          initials: "D.",
          last_name: "Aygün",
          locality: "Heemdamseburg",
          gender: "Female",
        },
      ],
    },
    {
      number: 3,
      name: "KEUS",
      candidates: [
        {
          number: 1,
          initials: "Y.M.",
          first_name: "Yağmur",
          last_name: "Boermans",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 2,
          initials: "R.",
          first_name: "Renso",
          last_name: "Born",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 3,
          initials: "S.",
          first_name: "Sijtze",
          last_name: "Groenen",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sijtze",
          last_name: "Titulaer",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 5,
          initials: "J.",
          first_name: "Jory",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 6,
          initials: "Z.",
          first_name: "Silvana",
          last_name: "Meulenkolk",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 7,
          initials: "A.Z.A.",
          first_name: "Alek",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 8,
          initials: "D.G.",
          first_name: "Damian",
          last_name: "Philippen",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 9,
          initials: "S.",
          first_name: "Sijtze",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 10,
          initials: "J.",
          first_name: "Jory",
          last_name: "Güneş",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 11,
          initials: "S.C.",
          first_name: "Sammie",
          last_name: "Aygün",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 12,
          initials: "R.J.",
          first_name: "Rachid",
          last_name: "Titulaer",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 13,
          initials: "R.M.",
          first_name: "Rachid",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 14,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Tax",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 15,
          initials: "K.",
          first_name: "Kris",
          last_name: "Titulaer",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 16,
          initials: "K.O.",
          first_name: "Kris",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 17,
          initials: "J.",
          first_name: "Jory",
          last_name: "Arets",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 18,
          initials: "N.",
          first_name: "Nicolaas",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 19,
          initials: "J.B.",
          first_name: "Jory",
          last_name: "Wiertz",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 20,
          initials: "İ.X.Q.",
          first_name: "İlknur",
          last_name: "Meulenkolk",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 21,
          initials: "S.Z.O.",
          first_name: "Sijtze",
          last_name: "Gopal",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 22,
          initials: "S.E.",
          first_name: "Salomon",
          last_name: "Tax",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 23,
          initials: "R.O.",
          first_name: "Royce",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 24,
          initials: "G.I.H.",
          first_name: "Gijsbertje",
          last_name: "Oorschot",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 25,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Arets",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 26,
          initials: "D.",
          first_name: "Damian",
          last_name: "Arets",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 27,
          initials: "A.",
          first_name: "Alek",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 28,
          initials: "G.I.",
          first_name: "Gijsbertje",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 29,
          initials: "F.X.H.",
          first_name: "Florien",
          last_name: "Born",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 30,
          initials: "N.",
          first_name: "Nikky",
          last_name: "Wiertz",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 31,
          initials: "G.P.L.",
          first_name: "Gijsbertje",
          last_name: "Titulaer",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 32,
          initials: "K.O.",
          first_name: "Kris",
          last_name: "Titulaer",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 33,
          initials: "K.",
          first_name: "Kris",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 34,
          initials: "S.",
          first_name: "Silvana",
          last_name: "Wolfswinkel",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 35,
          initials: "E.B.",
          first_name: "Esra",
          last_name: "Groenen",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 36,
          initials: "S.Q.",
          first_name: "Sibel",
          last_name: "Meulenkolk",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 37,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Boermans",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 38,
          initials: "R.",
          first_name: "Rachid",
          last_name: "Aygün",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 39,
          initials: "Y.",
          first_name: "Yağmur",
          last_name: "Wiertz",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 40,
          initials: "A.S.H.",
          first_name: "Alek",
          last_name: "Born",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 41,
          initials: "Y.",
          first_name: "Yağmur",
          last_name: "Brienen",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 42,
          initials: "S.",
          first_name: "Sammie",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 43,
          initials: "P.",
          first_name: "Royce",
          last_name: "Tax",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 44,
          initials: "M.M.Z.N.",
          first_name: "Madelène",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 45,
          initials: "S.",
          first_name: "Salomon",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 46,
          initials: "C.O.U.",
          first_name: "Cornelus",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 47,
          initials: "A.",
          first_name: "Alek",
          last_name: "Oorschot",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 48,
          initials: "R.Z.",
          first_name: "Renso",
          last_name: "Tax",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 49,
          initials: "T.N.",
          first_name: "Tiemen",
          last_name: "Gopal",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 50,
          initials: "L.G.I.S.",
          first_name: "Leontien",
          last_name: "Philippen",
          locality: "Eksterlo",
          gender: "Female",
        },
      ],
    },
    {
      number: 4,
      name: "Algemene Lijst",
      candidates: [
        {
          number: 1,
          initials: "D.B.",
          first_name: "Dirk-Jan",
          last_name: "Boermans",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 2,
          initials: "E.W.",
          first_name: "Edis",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 3,
          initials: "C.Y.",
          first_name: "Christina",
          last_name: "Meulenkolk",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 4,
          initials: "E.Y.",
          first_name: "Esra",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 5,
          initials: "K.",
          first_name: "Kris",
          last_name: "Meulenkolk",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 6,
          initials: "B.G.Z.",
          first_name: "Bart",
          last_name: "Arets",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 7,
          initials: "R.W.",
          first_name: "Renso",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 8,
          initials: "X.M.I.",
          first_name: "Nikky",
          last_name: "Wolfswinkel",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 9,
          initials: "J.",
          first_name: "Jory",
          last_name: "Wolfswinkel",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 10,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name: "Groenen",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 11,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Boermans",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 12,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Cornelis",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 13,
          initials: "S.",
          first_name: "Salomon",
          last_name: "Born",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 14,
          initials: "C.",
          first_name: "Cornelus",
          last_name: "Aygün",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 15,
          initials: "B.",
          first_name: "Bart",
          last_name: "Prakken",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 16,
          initials: "O.Y.",
          first_name: "Rachid",
          last_name: "Brienen",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 17,
          initials: "Y.X.",
          first_name: "Yağmur",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 18,
          initials: "S.N.",
          first_name: "Sammie",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 19,
          initials: "S.D.",
          first_name: "Silvana",
          last_name: "Titulaer",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 20,
          initials: "D.",
          first_name: "Leontien",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 21,
          initials: "E.B.G.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 22,
          initials: "S.U.U.",
          first_name: "Silvana",
          last_name: "Wiertz",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 23,
          initials: "R.",
          first_name: "Rachid",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 24,
          initials: "T.",
          first_name: "Teun",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 25,
          initials: "N.",
          first_name: "Nicolaas",
          last_name: "Boermans",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 26,
          initials: "S.G.",
          first_name: "Sammie",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 27,
          initials: "S.C.",
          first_name: "Sijtze",
          last_name: "Arets",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 28,
          initials: "B.I.T.X.Q.W.",
          first_name: "Bart",
          last_name: "Meulenkolk",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 29,
          initials: "C.",
          first_name: "Cornelus",
          last_name: "Gopal",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 30,
          initials: "E.",
          first_name: "Eelko",
          last_name: "Katsma",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 31,
          initials: "İ.",
          first_name: "İlknur",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 32,
          initials: "H.M.",
          first_name: "Henk",
          last_name: "Gopal",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 33,
          initials: "L.X.",
          first_name: "Leontien",
          last_name: "Goedhart",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 34,
          initials: "R.A.",
          first_name: "Ruth",
          last_name: "Born",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 35,
          initials: "Y.A.",
          first_name: "Yağmur",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 36,
          initials: "E.C.",
          first_name: "Edis",
          last_name: "Goedhart",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 37,
          initials: "Y.W.",
          first_name: "Yağmur",
          last_name: "Bruins-Van den Kerk",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 38,
          initials: "A.",
          first_name: "Bart",
          last_name: "Groenen",
          locality: "Heemdamseburg",
          gender: "X",
        },
        {
          number: 39,
          initials: "B.N.S.P.",
          first_name: "Bart",
          last_name: "Bruins-Van den Kerk",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 40,
          initials: "C.P.",
          first_name: "Christina",
          last_name: "Wiertz",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 41,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Brienen",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 42,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Wolfswinkel",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 43,
          initials: "S.R.",
          first_name: "Sibel",
          last_name: "Brienen",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 44,
          initials: "R.O.",
          first_name: "Renso",
          last_name: "Groenen",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 45,
          initials: "L.L.S.",
          first_name: "Rachid",
          last_name: "Prakken",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 46,
          initials: "S.",
          first_name: "Sammie",
          last_name: "Güneş",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 47,
          initials: "R.I.",
          first_name: "Renso",
          last_name: "Philippen",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 48,
          initials: "B.",
          first_name: "Bart",
          last_name: "Bruins-Van den Kerk",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 49,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Katsma",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 50,
          initials: "S.W.",
          first_name: "Salomon",
          last_name: "Wolfswinkel",
          locality: "Huisden",
          gender: "X",
        },
      ],
    },
    {
      number: 5,
      name: "Unie van kandidaten",
      candidates: [
        {
          number: 1,
          initials: "L.",
          first_name: "Leontien",
          last_name: "Groenen",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 2,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name: "Katsma",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 3,
          initials: "J.",
          first_name: "Jelisa",
          last_name: "Bruins-Van den Kerk",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 4,
          initials: "A.D.",
          first_name: "Alek",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 5,
          initials: "S.Z.",
          first_name: "Sijtze",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 6,
          initials: "S.",
          first_name: "Sammie",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 7,
          initials: "Y.J.P.D.T.H.",
          first_name: "Yağmur",
          last_name: "Wolfswinkel",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 8,
          initials: "X.",
          first_name: "Jory",
          last_name: "Philippen",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 9,
          initials: "E.",
          first_name: "Eelko",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 10,
          initials: "E.J.",
          first_name: "Edis",
          last_name: "Güneş",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 11,
          initials: "C.P.R.",
          first_name: "Christina",
          last_name: "Hoogstraten",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 12,
          initials: "M.A.",
          first_name: "Madelène",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 13,
          initials: "M.G.L.",
          first_name: "Madelène",
          last_name: "Titulaer",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 14,
          initials: "R.N.",
          first_name: "Rachid",
          last_name: "Katsma",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 15,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Aygün",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 16,
          initials: "T.Q.",
          first_name: "Teun",
          last_name: "Philippen",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 17,
          initials: "N.F.",
          first_name: "Nicolaas",
          last_name: "Gopal",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 18,
          initials: "A.T.",
          first_name: "Alek",
          last_name: "Goedhart",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 19,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Oorschot",
          locality: "Heemdamseburg",
          gender: "X",
        },
        {
          number: 20,
          initials: "İ.J.",
          first_name: "İlknur",
          last_name: "Brienen",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 21,
          initials: "N.D.",
          first_name: "Nikky",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 22,
          initials: "E.",
          first_name: "Eelko",
          last_name: "Gopal",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 23,
          initials: "R.",
          first_name: "Royce",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 24,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 25,
          initials: "N.D.",
          first_name: "Nikky",
          last_name: "Bruins-Van den Kerk",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 26,
          initials: "Z.",
          first_name: "Royce",
          last_name: "Meulenkolk",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 27,
          initials: "A.",
          first_name: "Alek",
          last_name: "Brienen",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 28,
          initials: "J.",
          first_name: "Jelisa",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 29,
          initials: "Y.E.",
          first_name: "Yağmur",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 30,
          initials: "T.",
          first_name: "Tiemen",
          last_name: "Oorschot",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 31,
          initials: "S.",
          first_name: "Salomon",
          last_name: "Oorschot",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 32,
          initials: "H.",
          first_name: "Henk",
          last_name: "Güneş",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 33,
          initials: "E.J.",
          first_name: "Edis",
          last_name: "Groenen",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 34,
          initials: "J.",
          first_name: "Jory",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 35,
          initials: "N.O.M.G.",
          first_name: "Nicolaas",
          last_name: "Güneş",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 36,
          initials: "D.",
          first_name: "Damian",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 37,
          initials: "T.",
          first_name: "Teun",
          last_name: "Brienen",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 38,
          initials: "A.",
          first_name: "Alek",
          last_name: "Bruins-Van den Kerk",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 39,
          initials: "R.",
          first_name: "Renso",
          last_name: "Wolfswinkel",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 40,
          initials: "R.",
          first_name: "Royce",
          last_name: "Born",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 41,
          initials: "S.",
          first_name: "Sibel",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 42,
          initials: "F.Z.",
          first_name: "Florien",
          last_name: "Philippen",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 43,
          initials: "S.K.",
          first_name: "Silvana",
          last_name: "Philippen",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 44,
          initials: "R.D.",
          first_name: "Renso",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 45,
          initials: "B.",
          first_name: "Bart",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 46,
          initials: "A.R.",
          first_name: "Alek",
          last_name: "Boermans",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 47,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Groenen",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 48,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 49,
          initials: "C.",
          first_name: "Cornelus",
          last_name: "Titulaer",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 50,
          initials: "N.U.",
          first_name: "Nikky",
          last_name: "Arets",
          locality: "Lekkum",
          gender: "X",
        },
      ],
    },
    {
      number: 6,
      name: "Lijst van stemmers",
      candidates: [
        {
          number: 1,
          initials: "E.",
          first_name: "Eelko",
          last_name: "Cornelis",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 2,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Goedhart",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 3,
          initials: "D.",
          first_name: "Damian",
          last_name: "Wolfswinkel",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 4,
          initials: "T.",
          first_name: "Tiemen",
          last_name: "Tax",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 5,
          initials: "B.D.A.",
          first_name: "Cornelus",
          last_name: "Brienen",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 6,
          initials: "R.A.",
          first_name: "Royce",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 7,
          initials: "J.V.C.",
          first_name: "Jelisa",
          last_name: "Bruins-Van den Kerk",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 8,
          initials: "Y.",
          first_name: "Teun",
          last_name: "Groenen",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 9,
          initials: "B.",
          first_name: "Bart",
          last_name: "Cornelis",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 10,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Goedhart",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 11,
          initials: "D.J.C.",
          first_name: "Damian",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 12,
          initials: "A.A.C.",
          first_name: "Dirk-Jan",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 13,
          initials: "N.",
          first_name: "Nikky",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 14,
          initials: "A.",
          first_name: "Alek",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 15,
          initials: "S.",
          first_name: "Silvana",
          last_name: "Bruins-Van den Kerk",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 16,
          initials: "J.F.",
          first_name: "Jelisa",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 17,
          initials: "Y.Q.",
          first_name: "Yağmur",
          last_name: "Wiertz",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 18,
          initials: "S.O.",
          first_name: "Sijtze",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 19,
          initials: "J.C.",
          first_name: "Jory",
          last_name: "Bruins-Van den Kerk",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 20,
          initials: "E.",
          first_name: "Eelko",
          last_name: "Wiertz",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 21,
          initials: "L.I.C.",
          first_name: "Leontien",
          last_name: "Wolfswinkel",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 22,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 23,
          initials: "R.",
          first_name: "Rachid",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 24,
          initials: "J.",
          first_name: "Jelisa",
          last_name: "Güneş",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 25,
          initials: "T.",
          first_name: "Tiemen",
          last_name: "Katsma",
          locality: "Hovenerwoud",
          gender: "Female",
        },
        {
          number: 26,
          initials: "J.",
          first_name: "Eelko",
          last_name: "Katsma",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 27,
          initials: "W.",
          first_name: "Royce",
          last_name: "Arets",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 28,
          initials: "R.",
          first_name: "Rachid",
          last_name: "Boermans",
          locality: "Hovenerwoud",
          gender: "Male",
        },
        {
          number: 29,
          initials: "S.",
          first_name: "Sibel",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Hoek van Zoom",
          gender: "Male",
        },
        {
          number: 30,
          initials: "N.O.Q.U.",
          first_name: "Nicolaas",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 31,
          initials: "H.X.",
          first_name: "Henk",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 32,
          initials: "K.J.J.",
          first_name: "Kris",
          last_name: "Arets",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 33,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 34,
          initials: "S.",
          first_name: "Sammie",
          last_name: "Arets",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 35,
          initials: "F.",
          first_name: "Florien",
          last_name: "Groenen",
          locality: "Eksterlo",
          gender: "Male",
        },
        {
          number: 36,
          initials: "Y.",
          first_name: "Yağmur",
          last_name: "Tax",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 37,
          initials: "Q.D.",
          first_name: "Renso",
          last_name: "Gopal",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 38,
          initials: "S.B.",
          first_name: "Jelisa",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 39,
          initials: "J.",
          first_name: "Jelisa",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 40,
          initials: "G.E.",
          first_name: "Gijsbertje",
          last_name: "Oorschot",
          locality: "Hoek van Zoom",
          gender: "X",
        },
        {
          number: 41,
          initials: "C.",
          first_name: "Cornelus",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 42,
          initials: "M.",
          first_name: "Madelène",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 43,
          initials: "Y.",
          first_name: "Yağmur",
          last_name_prefix: "van de",
          last_name: "Wal",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 44,
          initials: "D.",
          first_name: "Damian",
          last_name: "Prakken",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 45,
          initials: "S.R.",
          first_name: "Silvana",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 46,
          initials: "T.V.",
          first_name: "Teun",
          last_name: "Aygün",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 47,
          initials: "L.I.",
          first_name: "Leontien",
          last_name: "Born",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 48,
          initials: "B.L.Z.",
          first_name: "Bart",
          last_name: "Aygün",
          locality: "Heemdamseburg",
          gender: "Female",
        },
        {
          number: 49,
          initials: "R.",
          first_name: "Royce",
          last_name: "Wolfswinkel",
          locality: "Lekkum",
          gender: "Male",
        },
        {
          number: 50,
          initials: "D.Z.S.Y.",
          first_name: "Dirk-Jan",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Eemstricht",
          gender: "X",
        },
      ],
    },
  ],
};
