import {
  CandidateNominationResult,
  Election,
  ElectionSummary,
  PoliticalGroup,
  PoliticalGroupCandidateNomination,
  PoliticalGroupVotes,
  SeatAssignmentResult,
  SeatChangeStep,
} from "@/api/gen/openapi";

import { HighestAverageAssignmentStep, LargestRemainderAssignmentStep } from "../utils/seat-change";

export const largest_remainder_steps: LargestRemainderAssignmentStep[] = [
  {
    residual_seat_number: 1,
    change: {
      changed_by: "LargestRemainderAssignment",
      selected_pg_number: 2,
      pg_options: [2],
      pg_assigned: [2],
      remainder_votes: {
        integer: 60,
        numerator: 0,
        denominator: 15,
      },
    },
    standings: [
      {
        pg_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 73,
          numerator: 5,
          denominator: 11,
        },
        full_seats: 10,
        residual_seats: 0,
      },
      {
        pg_number: 2,
        votes_cast: 60,
        remainder_votes: {
          integer: 60,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 60,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 8,
        votes_cast: 52,
        remainder_votes: {
          integer: 52,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 52,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 2,
    change: {
      changed_by: "LargestRemainderAssignment",
      selected_pg_number: 1,
      pg_options: [1],
      pg_assigned: [1],
      remainder_votes: {
        integer: 8,
        numerator: 0,
        denominator: 15,
      },
    },
    standings: [
      {
        pg_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 73,
          numerator: 5,
          denominator: 11,
        },
        full_seats: 10,
        residual_seats: 0,
      },
      {
        pg_number: 2,
        votes_cast: 60,
        remainder_votes: {
          integer: 60,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 30,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        pg_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 8,
        votes_cast: 52,
        remainder_votes: {
          integer: 52,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 52,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
];

export const highest_average_steps: HighestAverageAssignmentStep[] = [
  {
    residual_seat_number: 3,
    change: {
      changed_by: "HighestAverageAssignment",
      selected_pg_number: 1,
      pg_options: [1],
      pg_assigned: [1],
      votes_per_seat: {
        integer: 67,
        numerator: 4,
        denominator: 12,
      },
    },
    standings: [
      {
        pg_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 67,
          numerator: 4,
          denominator: 12,
        },
        full_seats: 10,
        residual_seats: 1,
      },
      {
        pg_number: 2,
        votes_cast: 60,
        remainder_votes: {
          integer: 60,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 30,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        pg_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 8,
        votes_cast: 52,
        remainder_votes: {
          integer: 52,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 52,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 4,
    change: {
      changed_by: "HighestAverageAssignment",
      selected_pg_number: 3,
      pg_options: [3],
      pg_assigned: [3],
      votes_per_seat: {
        integer: 58,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        pg_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 62,
          numerator: 2,
          denominator: 13,
        },
        full_seats: 10,
        residual_seats: 2,
      },
      {
        pg_number: 2,
        votes_cast: 60,
        remainder_votes: {
          integer: 60,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 30,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        pg_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 8,
        votes_cast: 52,
        remainder_votes: {
          integer: 52,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 52,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 5,
    change: {
      changed_by: "HighestAverageAssignment",
      selected_pg_number: 4,
      pg_options: [4],
      pg_assigned: [4],
      votes_per_seat: {
        integer: 57,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        pg_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 62,
          numerator: 2,
          denominator: 13,
        },
        full_seats: 10,
        residual_seats: 2,
      },
      {
        pg_number: 2,
        votes_cast: 60,
        remainder_votes: {
          integer: 60,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 30,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        pg_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        pg_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        pg_number: 8,
        votes_cast: 52,
        remainder_votes: {
          integer: 52,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 52,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
];

export const seat_assignment: SeatAssignmentResult = {
  seats: 15,
  full_seats: 10,
  residual_seats: 5,
  quota: {
    integer: 80,
    numerator: 0,
    denominator: 15,
  },
  steps: (largest_remainder_steps as SeatChangeStep[]).concat(highest_average_steps),
  final_standing: [
    {
      pg_number: 1,
      votes_cast: 808,
      remainder_votes: {
        integer: 8,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 10,
      residual_seats: 2,
      total_seats: 12,
    },
    {
      pg_number: 2,
      votes_cast: 60,
      remainder_votes: {
        integer: 60,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      pg_number: 3,
      votes_cast: 58,
      remainder_votes: {
        integer: 58,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      pg_number: 4,
      votes_cast: 57,
      remainder_votes: {
        integer: 57,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      pg_number: 5,
      votes_cast: 56,
      remainder_votes: {
        integer: 56,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      pg_number: 6,
      votes_cast: 55,
      remainder_votes: {
        integer: 55,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      pg_number: 7,
      votes_cast: 54,
      remainder_votes: {
        integer: 54,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      pg_number: 8,
      votes_cast: 52,
      remainder_votes: {
        integer: 52,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
  ],
};

export const political_group_1_candidate_nomination: PoliticalGroupCandidateNomination = {
  pg_number: 1,
  pg_name: "Political Group A",
  pg_seats: 12,
  preferential_candidate_nomination: [
    {
      number: 12,
      votes: 200,
    },
    {
      number: 1,
      votes: 138,
    },
    {
      number: 6,
      votes: 100,
    },
    {
      number: 7,
      votes: 60,
    },
    {
      number: 3,
      votes: 55,
    },
    {
      number: 5,
      votes: 50,
    },
    {
      number: 11,
      votes: 50,
    },
    {
      number: 4,
      votes: 45,
    },
    {
      number: 8,
      votes: 40,
    },
  ],
  other_candidate_nomination: [
    {
      number: 2,
      votes: 20,
    },
    {
      number: 9,
      votes: 30,
    },
    {
      number: 10,
      votes: 20,
    },
  ],
  updated_candidate_ranking: [
    {
      number: 12,
      initials: "K.",
      first_name: "Karin",
      last_name: "Kok",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "L.",
      first_name: "Lidewij",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 6,
      initials: "B.",
      first_name: "Berta",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 7,
      initials: "K.",
      first_name: "Klaas",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 3,
      initials: "M.",
      first_name: "Marijke",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 5,
      initials: "H.",
      first_name: "Henk",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 11,
      initials: "R.",
      first_name: "Rolf",
      last_name_prefix: "de",
      last_name: "Jong",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 4,
      initials: "A.",
      first_name: "Arie",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 8,
      initials: "S.",
      first_name: "Sophie",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "J.",
      first_name: "Johan",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 9,
      initials: "J.",
      first_name: "Johan",
      last_name_prefix: "de",
      last_name: "Vries",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 10,
      initials: "M.",
      first_name: "Marijke",
      last_name_prefix: "van den",
      last_name: "Berg",
      locality: "Test Location",
      gender: "Female",
    },
  ],
};

export const political_group_5_candidate_nomination: PoliticalGroupCandidateNomination = {
  pg_number: 5,
  pg_name: "Political Group E",
  pg_seats: 0,
  preferential_candidate_nomination: [],
  other_candidate_nomination: [],
  updated_candidate_ranking: [],
};

export const candidate_nomination: CandidateNominationResult = {
  preference_threshold: {
    percentage: 50,
    number_of_votes: {
      integer: 40,
      numerator: 0,
      denominator: 1500,
    },
  },
  chosen_candidates: [
    {
      number: 8,
      initials: "S.",
      first_name: "Sophie",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "T.",
      first_name: "Tinus",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 10,
      initials: "M.",
      first_name: "Marijke",
      last_name_prefix: "van den",
      last_name: "Berg",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "G.",
      first_name: "Gerard",
      last_name: "Bogaert",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 1,
      initials: "A.",
      first_name: "Adelbert",
      last_name_prefix: "van",
      last_name: "Doorn",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 4,
      initials: "A.",
      first_name: "Arie",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 11,
      initials: "R.",
      first_name: "Rolf",
      last_name_prefix: "de",
      last_name: "Jong",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 12,
      initials: "K.",
      first_name: "Karin",
      last_name: "Kok",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 1,
      initials: "L.",
      first_name: "Lidewij",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "J.",
      first_name: "Johan",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 3,
      initials: "M.",
      first_name: "Marijke",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 7,
      initials: "K.",
      first_name: "Klaas",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 9,
      initials: "J.",
      first_name: "Johan",
      last_name_prefix: "de",
      last_name: "Vries",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 5,
      initials: "H.",
      first_name: "Henk",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 6,
      initials: "B.",
      first_name: "Berta",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Female",
    },
  ],
  political_group_candidate_nomination: [
    political_group_1_candidate_nomination,
    {
      pg_number: 2,
      pg_name: "Political Group B",
      pg_seats: 1,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [
        {
          number: 1,
          votes: 20,
        },
      ],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 3,
      pg_name: "Political Group C",
      pg_seats: 1,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [
        {
          number: 1,
          votes: 20,
        },
      ],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 4,
      pg_name: "Political Group D",
      pg_seats: 1,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [
        {
          number: 1,
          votes: 20,
        },
      ],
      updated_candidate_ranking: [],
    },
    political_group_5_candidate_nomination,
    {
      pg_number: 6,
      pg_name: "Political Group F",
      pg_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 7,
      pg_name: "Political Group G",
      pg_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      pg_number: 8,
      pg_name: "Political Group H",
      pg_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
  ],
};

export const political_group_1_votes: PoliticalGroupVotes = {
  number: 1,
  total: 808,
  candidate_votes: [
    {
      number: 1,
      votes: 138,
    },
    {
      number: 2,
      votes: 20,
    },
    {
      number: 3,
      votes: 55,
    },
    {
      number: 4,
      votes: 45,
    },
    {
      number: 5,
      votes: 50,
    },
    {
      number: 6,
      votes: 100,
    },
    {
      number: 7,
      votes: 60,
    },
    {
      number: 8,
      votes: 40,
    },
    {
      number: 9,
      votes: 30,
    },
    {
      number: 10,
      votes: 20,
    },
    {
      number: 11,
      votes: 50,
    },
    {
      number: 12,
      votes: 200,
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 1200,
    proxy_certificate_count: 2,
    voter_card_count: 3,
    total_admitted_voters_count: 1205,
  },
  votes_counts: {
    votes_candidates_count: 1200,
    blank_votes_count: 3,
    invalid_votes_count: 2,
    total_votes_cast_count: 1205,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    fewer_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    unreturned_ballots_count: {
      count: 0,
      polling_stations: [],
    },
    too_few_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    too_many_ballots_handed_out_count: {
      count: 0,
      polling_stations: [],
    },
    other_explanation_count: {
      count: 0,
      polling_stations: [],
    },
    no_explanation_count: {
      count: 0,
      polling_stations: [],
    },
  },
  recounted_polling_stations: [],
  political_group_votes: [
    political_group_1_votes,
    {
      number: 2,
      total: 60,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 2,
        },
        {
          number: 6,
          votes: 15,
        },
      ],
    },
    {
      number: 3,
      total: 58,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 2,
        },
        {
          number: 6,
          votes: 13,
        },
      ],
    },
    {
      number: 4,
      total: 57,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 14,
        },
      ],
    },
    {
      number: 5,
      total: 56,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 16,
        },
      ],
    },
    {
      number: 6,
      total: 55,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 15,
        },
      ],
    },
    {
      number: 7,
      total: 54,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 14,
        },
      ],
    },
    {
      number: 8,
      total: 52,
      candidate_votes: [
        {
          number: 1,
          votes: 32,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
      ],
    },
  ],
};

export const political_group_1: PoliticalGroup = {
  number: 1,
  name: "Political Group A",
  candidates: [
    {
      number: 1,
      initials: "L.",
      first_name: "Lidewij",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 2,
      initials: "J.",
      first_name: "Johan",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 3,
      initials: "M.",
      first_name: "Marijke",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 4,
      initials: "A.",
      first_name: "Arie",
      last_name: "Jansen",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 5,
      initials: "H.",
      first_name: "Henk",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 6,
      initials: "B.",
      first_name: "Berta",
      last_name_prefix: "van der",
      last_name: "Weijden",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 7,
      initials: "K.",
      first_name: "Klaas",
      last_name: "Oud",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 8,
      initials: "S.",
      first_name: "Sophie",
      last_name: "Bakker",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 9,
      initials: "J.",
      first_name: "Johan",
      last_name_prefix: "de",
      last_name: "Vries",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 10,
      initials: "M.",
      first_name: "Marijke",
      last_name_prefix: "van den",
      last_name: "Berg",
      locality: "Test Location",
      gender: "Female",
    },
    {
      number: 11,
      initials: "R.",
      first_name: "Rolf",
      last_name_prefix: "de",
      last_name: "Jong",
      locality: "Test Location",
      gender: "Male",
    },
    {
      number: 12,
      initials: "K.",
      first_name: "Karin",
      last_name: "Kok",
      locality: "Test Location",
      gender: "Female",
    },
  ],
};

export const election: Election = {
  id: 3,
  name: "Test Election < 19 seats",
  location: "Test Location",
  number_of_voters: 2000,
  category: "Municipal",
  number_of_seats: 15,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  status: "DataEntryFinished",
  political_groups: [
    political_group_1,
    {
      number: 2,
      name: "Political Group B",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tinus",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "D.",
          last_name: "Po",
          locality: "Test Location",
          gender: "X",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Willem",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Kloosterboer",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "L.",
          first_name: "Liesbeth",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 6,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van den",
          last_name: "Berg",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 3,
      name: "Political Group C",
      candidates: [
        {
          number: 1,
          initials: "A.",
          first_name: "Adelbert",
          last_name_prefix: "van",
          last_name: "Doorn",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "M.",
          first_name: "Margriet",
          last_name_prefix: "van der",
          last_name: "Linden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "P.",
          first_name: "Paul",
          last_name: "Veldkamp",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sophie",
          last_name_prefix: "de",
          last_name: "Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "R.",
          first_name: "Rik",
          last_name_prefix: "de",
          last_name: "Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "N.",
          first_name: "Nico",
          last_name: "Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 4,
      name: "Political Group D",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gerard",
          last_name: "Bogaert",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Jan",
          last_name: "Stevens",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "E.",
          first_name: "Els",
          last_name: "Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "B.",
          first_name: "Bart",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "F.",
          first_name: "Frits",
          last_name: "Veldman",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 5,
      name: "Political Group E",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Eva",
          last_name: "Koster",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "L.",
          first_name: "Leon",
          last_name: "Hofman",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Visser",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 6,
      name: "Political Group F",
      candidates: [
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "P.",
          first_name: "Piet",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "A.",
          first_name: "Annelies",
          last_name_prefix: "van",
          last_name: "Loon",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "T.J.",
          first_name: "Tessa",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 7,
      name: "Political Group G",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Hans",
          last_name_prefix: "van der",
          last_name: "Vaart",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.H.",
          first_name: "Tjolkse Hendrika",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 8,
      name: "Political Group H",
      candidates: [
        {
          number: 1,
          initials: "F.",
          first_name: "Frederik",
          last_name: "Jacobse",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.J.",
          first_name: "Tedje Johannes",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "K.",
          first_name: "Karel",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
  ],
};
