import type {
  ApportionmentState,
  CandidateNomination,
  CommitteeSession,
  ElectionSummary,
  ElectionWithPoliticalGroups,
  SeatAssignment,
} from "@/types/generated/openapi";

export const state: ApportionmentState = {
  type: "Finalised",
  deceased_candidates: [
    {
      pg_number: 3,
      candidate_number: 1,
    },
  ],
  lists_drawn: [],
  candidates_drawn: [],
};

export const seat_assignment: SeatAssignment = {
  seats: 10,
  full_seats: 5,
  residual_seats: 5,
  quota: {
    integer: 99,
    numerator: 5,
    denominator: 10,
  },
  steps: [
    {
      residual_seat_number: 1,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_list_number: 1,
        list_options: [1],
        list_assigned: [1],
        remainder_votes: {
          integer: 17,
          numerator: 5,
          denominator: 10,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 85,
            numerator: 5,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 74,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 73,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 72,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 2,
      change: {
        changed_by: "UniqueHighestAverageAssignment",
        selected_list_number: 2,
        list_options: [2],
        list_assigned: [2],
        list_exhausted: [],
        votes_per_seat: {
          integer: 74,
          numerator: 0,
          denominator: 1,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 73,
            numerator: 4,
            denominator: 7,
          },
          full_seats: 5,
          residual_seats: 1,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 74,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 73,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 72,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 3,
      change: {
        changed_by: "UniqueHighestAverageAssignment",
        selected_list_number: 1,
        list_options: [1],
        list_assigned: [1],
        list_exhausted: [],
        votes_per_seat: {
          integer: 73,
          numerator: 4,
          denominator: 7,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 73,
            numerator: 4,
            denominator: 7,
          },
          full_seats: 5,
          residual_seats: 1,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 37,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 73,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 72,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 4,
      change: {
        changed_by: "UniqueHighestAverageAssignment",
        selected_list_number: 3,
        list_options: [3],
        list_assigned: [3],
        list_exhausted: [],
        votes_per_seat: {
          integer: 73,
          numerator: 0,
          denominator: 1,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 64,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 5,
          residual_seats: 2,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 37,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 73,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 72,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 5,
      change: {
        changed_by: "UniqueHighestAverageAssignment",
        selected_list_number: 4,
        list_options: [4],
        list_assigned: [4],
        list_exhausted: [],
        votes_per_seat: {
          integer: 72,
          numerator: 0,
          denominator: 1,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 64,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 5,
          residual_seats: 2,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 37,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 36,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 72,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      change: {
        changed_by: "ListExhaustionRemoval",
        list_retracted_seat: 3,
        full_seat: false,
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 64,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 5,
          residual_seats: 2,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 37,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 36,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 36,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 6,
      change: {
        changed_by: "UniqueHighestAverageAssignment",
        selected_list_number: 5,
        list_options: [5],
        list_assigned: [5],
        list_exhausted: [3],
        votes_per_seat: {
          integer: 71,
          numerator: 0,
          denominator: 1,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 515,
          remainder_votes: {
            integer: 17,
            numerator: 5,
            denominator: 10,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 64,
            numerator: 3,
            denominator: 8,
          },
          full_seats: 5,
          residual_seats: 2,
        },
        {
          list_number: 2,
          votes_cast: 74,
          remainder_votes: {
            integer: 74,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 37,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 73,
          remainder_votes: {
            integer: 73,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 73,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 72,
          remainder_votes: {
            integer: 72,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 36,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 5,
          votes_cast: 71,
          remainder_votes: {
            integer: 71,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 71,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 70,
          remainder_votes: {
            integer: 70,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 70,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 60,
          remainder_votes: {
            integer: 60,
            numerator: 0,
            denominator: 10,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 60,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 515,
      remainder_votes: {
        integer: 17,
        numerator: 5,
        denominator: 10,
      },
      meets_remainder_threshold: true,
      full_seats: 5,
      residual_seats: 2,
      total_seats: 7,
    },
    {
      list_number: 2,
      votes_cast: 74,
      remainder_votes: {
        integer: 74,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 3,
      votes_cast: 73,
      remainder_votes: {
        integer: 73,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      list_number: 4,
      votes_cast: 72,
      remainder_votes: {
        integer: 72,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 5,
      votes_cast: 71,
      remainder_votes: {
        integer: 71,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 6,
      votes_cast: 70,
      remainder_votes: {
        integer: 70,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      list_number: 7,
      votes_cast: 60,
      remainder_votes: {
        integer: 60,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      list_number: 8,
      votes_cast: 60,
      remainder_votes: {
        integer: 60,
        numerator: 0,
        denominator: 10,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
  ],
};

export const candidate_nomination: CandidateNomination = {
  preference_threshold: {
    percentage: 50,
    number_of_votes: {
      integer: 49,
      numerator: 750,
      denominator: 1000,
    },
  },
  chosen_candidates: [
    {
      number: 6,
      initials: "H.",
      first_name: "Henk",
      last_name: "Aygün",
      locality: "Heemdamseburg",
      gender: "Male",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 1,
      initials: "D.",
      first_name: "Dirk-Jan",
      last_name: "Boermans",
      locality: "Eemstricht",
      gender: "Male",
      list_number: 5,
      list_name: "Stemmmers 22",
    },
    {
      number: 4,
      initials: "A.K.F.",
      first_name: "Alek",
      last_name: "Groenen",
      locality: "'s Gravenveen",
      gender: "Female",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 2,
      initials: "A.T.N.",
      first_name: "Eelko",
      last_name: "Groenen",
      locality: "Lekkum",
      gender: "X",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 1,
      initials: "T.S.",
      last_name_prefix: "van de",
      last_name: "Kerkhof",
      locality: "Lekkum",
      gender: "X",
      list_number: 4,
      list_name: "Unie van kandidaten",
    },
    {
      number: 1,
      initials: "J.O.C.",
      first_name: "Jory",
      last_name_prefix: "den",
      last_name: "Mateman",
      locality: "Juinen",
      gender: "X",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 7,
      initials: "D.",
      first_name: "Damian",
      last_name: "Prakken",
      locality: "Huisden",
      gender: "Female",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 3,
      initials: "D.S.",
      first_name: "Dirk-Jan",
      last_name_prefix: "van der",
      last_name: "Spek",
      locality: "Huisden",
      gender: "X",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
    {
      number: 1,
      initials: "R.F.",
      first_name: "Royce",
      last_name: "Wolfswinkel",
      locality: "Sluisdam",
      gender: "Male",
      list_number: 2,
      list_name: "Verkiespartij",
    },
    {
      number: 5,
      initials: "S.",
      first_name: "Sibel",
      last_name: "Wolfswinkel",
      locality: "'s Gravenveen",
      gender: "Male",
      list_number: 1,
      list_name: "Partij van de groepen",
    },
  ],
  list_candidate_nomination: [
    {
      list_number: 1,
      list_name: "Partij van de groepen",
      list_seats: 7,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 515,
        },
      ],
      other_candidate_nomination: [
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
      ],
      updated_candidate_ranking: [],
    },
    {
      list_number: 2,
      list_name: "Verkiespartij",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 74,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 3,
      list_name: "De Stemunie",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 4,
      list_name: "Unie van kandidaten",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 72,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 5,
      list_name: "Stemmmers 22",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 71,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 6,
      list_name: "Groep De Partij",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 7,
      list_name: "Politieke Groep der Kandidaten",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 8,
      list_name: "Kiesregelingsunie",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 995,
    proxy_certificate_count: 0,
    total_admitted_voters_count: 995,
  },
  votes_counts: {
    political_group_total_votes: [
      {
        number: 1,
        total: 515,
      },
      {
        number: 2,
        total: 74,
      },
      {
        number: 3,
        total: 73,
      },
      {
        number: 4,
        total: 72,
      },
      {
        number: 5,
        total: 71,
      },
      {
        number: 6,
        total: 70,
      },
      {
        number: 7,
        total: 60,
      },
      {
        number: 8,
        total: 60,
      },
    ],
    total_votes_candidates_count: 995,
    blank_votes_count: 0,
    invalid_votes_count: 0,
    total_votes_cast_count: 995,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
    fewer_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
  },
  political_group_votes: [
    {
      number: 1,
      total: 515,
      candidate_votes: [
        {
          number: 1,
          votes: 515,
        },
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
      ],
    },
    {
      number: 2,
      total: 74,
      candidate_votes: [
        {
          number: 1,
          votes: 74,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
    {
      number: 3,
      total: 73,
      candidate_votes: [
        {
          number: 1,
          votes: 73,
        },
      ],
    },
    {
      number: 4,
      total: 72,
      candidate_votes: [
        {
          number: 1,
          votes: 72,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
    {
      number: 5,
      total: 71,
      candidate_votes: [
        {
          number: 1,
          votes: 71,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
    {
      number: 6,
      total: 70,
      candidate_votes: [
        {
          number: 1,
          votes: 70,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
    {
      number: 7,
      total: 60,
      candidate_votes: [
        {
          number: 1,
          votes: 60,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
    {
      number: 8,
      total: 60,
      candidate_votes: [
        {
          number: 1,
          votes: 60,
        },
        {
          number: 2,
          votes: 0,
        },
      ],
    },
  ],
  polling_station_investigations: {
    admitted_voters_recounted: [],
    investigated_other_reason: [],
    ballots_recounted: [],
  },
  number_of_voters: 1166,
};

export const committee_session: CommitteeSession = {
  id: 13,
  number: 1,
  election_id: 13,
  status: "completed",
  location: "",
  start_date_time: "",
};

export const election: ElectionWithPoliticalGroups = {
  id: 13,
  name: "Election < 19 seats & List Exhaustion & Deceased Candidate",
  committee_category: "CSB",
  election_id: "GR2026_Juinen",
  location: "Juinen",
  domain_id: "0035",
  category: "Municipal",
  number_of_seats: 10,
  number_of_voters: 1,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  political_groups: [
    {
      number: 1,
      name: "Partij van de groepen",
      candidates: [
        {
          number: 1,
          initials: "J.O.C.",
          first_name: "Jory",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 2,
          initials: "A.T.N.",
          first_name: "Eelko",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 3,
          initials: "D.S.",
          first_name: "Dirk-Jan",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Huisden",
          gender: "X",
        },
        {
          number: 4,
          initials: "A.K.F.",
          first_name: "Alek",
          last_name: "Groenen",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 5,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Wolfswinkel",
          locality: "'s Gravenveen",
          gender: "Male",
        },
        {
          number: 6,
          initials: "H.",
          first_name: "Henk",
          last_name: "Aygün",
          locality: "Heemdamseburg",
          gender: "Male",
        },
        {
          number: 7,
          initials: "D.",
          first_name: "Damian",
          last_name: "Prakken",
          locality: "Huisden",
          gender: "Female",
        },
        {
          number: 8,
          initials: "R.",
          first_name: "Rachid",
          last_name: "Cornelis",
          locality: "Heemdamseburg",
          gender: "X",
        },
        {
          number: 9,
          initials: "R.V.D.",
          first_name: "Ruth",
          last_name: "Wolfswinkel",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 10,
          initials: "J.L.",
          first_name: "Jelisa",
          last_name: "Meulenkolk",
          locality: "Lekkum",
          gender: "Female",
        },
      ],
    },
    {
      number: 2,
      name: "Verkiespartij",
      candidates: [
        {
          number: 1,
          initials: "R.F.",
          first_name: "Royce",
          last_name: "Wolfswinkel",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 2,
          initials: "S.C.",
          first_name: "Sibel",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Juinen",
          gender: "Female",
        },
      ],
    },
    {
      number: 3,
      name: "De Stemunie",
      candidates: [
        {
          number: 1,
          initials: "R.O.",
          first_name: "Ruth",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Heemdamseburg",
          gender: "Female",
        },
      ],
    },
    {
      number: 4,
      name: "Unie van kandidaten",
      candidates: [
        {
          number: 1,
          initials: "T.S.",
          last_name_prefix: "van de",
          last_name: "Kerkhof",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 2,
          initials: "O.",
          last_name: "Arets",
          locality: "Sluisdam",
          gender: "Male",
        },
      ],
    },
    {
      number: 5,
      name: "Stemmmers 22",
      candidates: [
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk-Jan",
          last_name: "Boermans",
          locality: "Eemstricht",
          gender: "Male",
        },
        {
          number: 2,
          initials: "S.",
          first_name: "Silvana",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Lekkum",
          gender: "Male",
        },
      ],
    },
    {
      number: 6,
      name: "Groep De Partij",
      candidates: [
        {
          number: 1,
          initials: "S.H.V.",
          first_name: "Silvana",
          last_name: "Brienen",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 2,
          initials: "S.Z.",
          first_name: "Sammie",
          last_name: "Philippen",
          locality: "Juinen",
          gender: "Male",
        },
      ],
    },
    {
      number: 7,
      name: "Politieke Groep der Kandidaten",
      candidates: [
        {
          number: 1,
          initials: "L.",
          last_name: "Bruins-Van den Kerk",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 2,
          initials: "B.Y.U.",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Eksterlo",
          gender: "Female",
        },
      ],
    },
    {
      number: 8,
      name: "Kiesregelingsunie",
      candidates: [
        {
          number: 1,
          initials: "S.Z.R.E.",
          first_name: "Sammie",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "Female",
        },
        {
          number: 2,
          initials: "S.",
          first_name: "Sibel",
          last_name: "Wolfswinkel",
          locality: "Middelgein",
          gender: "X",
        },
      ],
    },
  ],
};
