import type {
  ApportionmentState,
  CandidateDrawingLotsVariant,
  CandidateNomination,
  CommitteeSession,
  ElectionSummary,
  ElectionWithPoliticalGroups,
  SeatAssignment,
} from "@/types/generated/openapi";

export const drawing_lots_required: CandidateDrawingLotsVariant & {
  variant: "CandidateDrawingLotsVariant";
} = {
  variant: "CandidateDrawingLotsVariant",
  list: 1,
  total_seats: 5,
  number_of_votes: 500,
  seat_numbers: [4, 5],
  options: [3, 4, 5],
};
export const state: ApportionmentState = {
  type: "DrawingLots",
  drawing_lots_required: {
    type: "CandidateDrawingLotsRequired",
    ...drawing_lots_required,
  },
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [],
};

export const drawing_lots_required_after_one_drawing_lots_candidate_assigned: CandidateDrawingLotsVariant & {
  variant: "CandidateDrawingLotsVariant";
} = {
  variant: "CandidateDrawingLotsVariant",
  list: 1,
  total_seats: 5,
  number_of_votes: 500,
  seat_numbers: [5],
  options: [3, 4],
};

export const state_after_one_drawing_lots_candidate_assigned: ApportionmentState = {
  type: "DrawingLots",
  drawing_lots_required: {
    type: "CandidateDrawingLotsRequired",
    ...drawing_lots_required_after_one_drawing_lots_candidate_assigned,
  },
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [
    {
      variant: {
        list: 1,
        total_seats: 5,
        number_of_votes: 500,
        seat_numbers: [4, 5],
        options: [3, 4, 5],
      },
      drawn: 5,
    },
  ],
};

export const drawing_lots_required_after_two_drawing_lots_candidate_assigned: CandidateDrawingLotsVariant & {
  variant: "CandidateDrawingLotsVariant";
} = {
  variant: "CandidateDrawingLotsVariant",
  list: 5,
  total_seats: 1,
  number_of_votes: 300,
  seat_numbers: [1],
  options: [1, 2],
};

export const state_after_two_drawing_lots_candidates_assigned: ApportionmentState = {
  type: "DrawingLots",
  drawing_lots_required: {
    type: "CandidateDrawingLotsRequired",
    ...drawing_lots_required_after_two_drawing_lots_candidate_assigned,
  },
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [
    {
      variant: {
        list: 1,
        total_seats: 5,
        number_of_votes: 500,
        seat_numbers: [4, 5],
        options: [3, 4, 5],
      },
      drawn: 5,
    },
    {
      variant: {
        list: 1,
        total_seats: 5,
        number_of_votes: 500,
        seat_numbers: [5],
        options: [3, 4],
      },
      drawn: 4,
    },
  ],
};

export const state_after_three_drawing_lots_candidates_assigned: ApportionmentState = {
  type: "Finalised",
  deceased_candidates: [],
  lists_drawn: [],
  candidates_drawn: [
    {
      variant: {
        list: 1,
        total_seats: 5,
        number_of_votes: 500,
        seat_numbers: [4, 5],
        options: [3, 4, 5],
      },
      drawn: 5,
    },
    {
      variant: {
        list: 1,
        total_seats: 5,
        number_of_votes: 500,
        seat_numbers: [5],
        options: [3, 4],
      },
      drawn: 4,
    },
    {
      variant: {
        list: 5,
        total_seats: 1,
        number_of_votes: 300,
        seat_numbers: [1],
        options: [1, 2],
      },
      drawn: 2,
    },
  ],
};

export const seat_assignment: SeatAssignment = {
  seats: 15,
  full_seats: 13,
  residual_seats: 2,
  quota: {
    integer: 593,
    numerator: 5,
    denominator: 15,
  },
  steps: [
    {
      residual_seat_number: 1,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_list_number: 2,
        list_options: [2],
        list_assigned: [2],
        remainder_votes: {
          integer: 520,
          numerator: 0,
          denominator: 15,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 3200,
          remainder_votes: {
            integer: 233,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 533,
            numerator: 2,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 2300,
          remainder_votes: {
            integer: 520,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 575,
            numerator: 0,
            denominator: 4,
          },
          full_seats: 3,
          residual_seats: 0,
        },
        {
          list_number: 3,
          votes_cast: 1500,
          remainder_votes: {
            integer: 313,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 500,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 1200,
          remainder_votes: {
            integer: 13,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 400,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 700,
          remainder_votes: {
            integer: 106,
            numerator: 10,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 350,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
    {
      residual_seat_number: 2,
      change: {
        changed_by: "LargestRemainderAssignment",
        selected_list_number: 3,
        list_options: [3],
        list_assigned: [3],
        remainder_votes: {
          integer: 313,
          numerator: 5,
          denominator: 15,
        },
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 3200,
          remainder_votes: {
            integer: 233,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 533,
            numerator: 2,
            denominator: 6,
          },
          full_seats: 5,
          residual_seats: 0,
        },
        {
          list_number: 2,
          votes_cast: 2300,
          remainder_votes: {
            integer: 520,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 460,
            numerator: 0,
            denominator: 5,
          },
          full_seats: 3,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 1500,
          remainder_votes: {
            integer: 313,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 500,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 4,
          votes_cast: 1200,
          remainder_votes: {
            integer: 13,
            numerator: 5,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 400,
            numerator: 0,
            denominator: 3,
          },
          full_seats: 2,
          residual_seats: 0,
        },
        {
          list_number: 5,
          votes_cast: 700,
          remainder_votes: {
            integer: 106,
            numerator: 10,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 350,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 1,
          residual_seats: 0,
        },
      ],
    },
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 3200,
      remainder_votes: {
        integer: 233,
        numerator: 5,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 5,
      residual_seats: 0,
      total_seats: 5,
    },
    {
      list_number: 2,
      votes_cast: 2300,
      remainder_votes: {
        integer: 520,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 3,
      residual_seats: 1,
      total_seats: 4,
    },
    {
      list_number: 3,
      votes_cast: 1500,
      remainder_votes: {
        integer: 313,
        numerator: 5,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 1,
      total_seats: 3,
    },
    {
      list_number: 4,
      votes_cast: 1200,
      remainder_votes: {
        integer: 13,
        numerator: 5,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 2,
      residual_seats: 0,
      total_seats: 2,
    },
    {
      list_number: 5,
      votes_cast: 700,
      remainder_votes: {
        integer: 106,
        numerator: 10,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 1,
      residual_seats: 0,
      total_seats: 1,
    },
  ],
};

export const candidate_nomination: CandidateNomination = {
  preference_threshold: {
    percentage: 50,
    number_of_votes: {
      integer: 296,
      numerator: 1000,
      denominator: 1500,
    },
  },
  chosen_candidates: [
    {
      number: 2,
      initials: "A.I.",
      last_name_prefix: "van",
      last_name: "Bekking",
      locality: "'s Gravenveen",
      gender: "X",
      list_number: 4,
      list_name: "GROEP 11",
    },
    {
      number: 6,
      initials: "M.",
      first_name: "Madelène",
      last_name: "Groenen",
      locality: "Sluisdam",
      gender: "Female",
      list_number: 3,
      list_name: "GROEP 10",
    },
    {
      number: 1,
      initials: "W.W.",
      last_name: "Hoogstraten",
      locality: "Middelgein",
      gender: "Female",
      list_number: 4,
      list_name: "GROEP 11",
    },
    {
      number: 5,
      initials: "E.",
      first_name: "Esra",
      last_name_prefix: "van",
      last_name: "Jaspers-Gezen",
      locality: "Juinen",
      gender: "X",
      list_number: 3,
      list_name: "GROEP 10",
    },
    {
      number: 1,
      initials: "R.M.",
      first_name: "Ruth",
      last_name: "Katsma",
      locality: "Sluisdam",
      gender: "Male",
      list_number: 3,
      list_name: "GROEP 10",
    },
    {
      number: 4,
      initials: "S.O.",
      first_name: "Sammie",
      last_name: "Katsma",
      locality: "Eksterlo",
      gender: "X",
      list_number: 1,
      list_name: "GROEP 8",
    },
    {
      number: 2,
      initials: "E.",
      first_name: "Esra",
      last_name_prefix: "van",
      last_name: "Lent",
      locality: "Eemstricht",
      gender: "Female",
      list_number: 1,
      list_name: "GROEP 8",
    },
    {
      number: 2,
      initials: "N.",
      first_name: "Cornelus",
      last_name_prefix: "van",
      last_name: "Lent",
      locality: "Hoek van Zoom",
      gender: "Female",
      list_number: 2,
      list_name: "GROEP 9",
    },
    {
      number: 6,
      initials: "B.",
      first_name: "Bart",
      last_name: "Meulenkolk",
      locality: "Hovenerwoud",
      gender: "X",
      list_number: 2,
      list_name: "GROEP 9",
    },
    {
      number: 3,
      initials: "G.",
      first_name: "Silvana",
      last_name: "Meulenkolk",
      locality: "Sluisdam",
      gender: "Female",
      list_number: 2,
      list_name: "GROEP 9",
    },
    {
      number: 5,
      initials: "F.G.",
      first_name: "Jory",
      last_name: "Philippen",
      locality: "Eemstricht",
      gender: "Female",
      list_number: 1,
      list_name: "GROEP 8",
    },
    {
      number: 6,
      initials: "J.W.Q.Y.",
      first_name: "Jelisa",
      last_name_prefix: "van der",
      last_name: "Spek",
      locality: "Middelgein",
      gender: "Male",
      list_number: 1,
      list_name: "GROEP 8",
    },
    {
      number: 1,
      initials: "R.",
      first_name: "Royce",
      last_name: "Wiertz",
      locality: "Eemstricht",
      gender: "Female",
      list_number: 2,
      list_name: "GROEP 9",
    },
    {
      number: 1,
      initials: "İ.",
      first_name: "İlknur",
      last_name: "Wiertz",
      locality: "Bloemstede",
      gender: "X",
      list_number: 1,
      list_name: "GROEP 8",
    },
    {
      number: 2,
      initials: "R.",
      first_name: "Ruth",
      last_name: "Wolfswinkel",
      locality: "'s Gravenveen",
      gender: "X",
      list_number: 5,
      list_name: "GROEP 12",
    },
  ],
  list_candidate_nomination: [
    {
      list_number: 1,
      list_name: "GROEP 8",
      list_seats: 5,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 600,
        },
        {
          number: 2,
          votes: 550,
        },
        {
          number: 6,
          votes: 550,
        },
        {
          number: 5,
          votes: 500,
        },
        {
          number: 4,
          votes: 500,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "İ.",
          first_name: "İlknur",
          last_name: "Wiertz",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 6,
          initials: "J.W.Q.Y.",
          first_name: "Jelisa",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Middelgein",
          gender: "Male",
        },
        {
          number: 5,
          initials: "F.G.",
          first_name: "Jory",
          last_name: "Philippen",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 4,
          initials: "S.O.",
          first_name: "Sammie",
          last_name: "Katsma",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 3,
          initials: "D.P.K.",
          first_name: "Damian",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Lekkum",
          gender: "X",
        },
      ],
    },
    {
      list_number: 2,
      list_name: "GROEP 9",
      list_seats: 4,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 6,
          votes: 450,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 2,
          votes: 350,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "R.",
          first_name: "Royce",
          last_name: "Wiertz",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Bart",
          last_name: "Meulenkolk",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 3,
          initials: "G.",
          first_name: "Silvana",
          last_name: "Meulenkolk",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 2,
          initials: "N.",
          first_name: "Cornelus",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 4,
          initials: "N.",
          first_name: "Nikky",
          last_name: "Arets",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 5,
          initials: "R.A.I.",
          first_name: "Rachid",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "X",
        },
      ],
    },
    {
      list_number: 3,
      list_name: "GROEP 10",
      list_seats: 3,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 6,
          votes: 350,
        },
        {
          number: 5,
          votes: 300,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "R.M.",
          first_name: "Ruth",
          last_name: "Katsma",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 6,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Groenen",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 5,
          initials: "E.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 2,
          initials: "K.",
          first_name: "Eelko",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 3,
          initials: "U.",
          first_name: "Royce",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 4,
          initials: "D.G.",
          first_name: "Dirk-Jan",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "Female",
        },
      ],
    },
    {
      list_number: 4,
      list_name: "GROEP 11",
      list_seats: 2,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 300,
        },
      ],
      other_candidate_nomination: [
        {
          number: 2,
          votes: 150,
        },
      ],
      updated_candidate_ranking: [],
    },
    {
      list_number: 5,
      list_name: "GROEP 12",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 2,
          votes: 300,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [
        {
          number: 2,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Wolfswinkel",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 1,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Wolfswinkel",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 3,
          initials: "İ.",
          first_name: "İlknur",
          last_name: "Güneş",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Kris",
          last_name: "Güneş",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 5,
          initials: "L.",
          first_name: "Leontien",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 6,
          initials: "Q.U.E.",
          first_name: "Rachid",
          last_name: "Wiertz",
          locality: "Bloemstede",
          gender: "Female",
        },
      ],
    },
  ],
};

export const election_summary: ElectionSummary = {
  voters_counts: {
    poll_card_count: 8900,
    proxy_certificate_count: 0,
    total_admitted_voters_count: 8900,
  },
  votes_counts: {
    political_group_total_votes: [
      {
        number: 1,
        total: 3200,
      },
      {
        number: 2,
        total: 2300,
      },
      {
        number: 3,
        total: 1500,
      },
      {
        number: 4,
        total: 1200,
      },
      {
        number: 5,
        total: 700,
      },
    ],
    total_votes_candidates_count: 8900,
    blank_votes_count: 0,
    invalid_votes_count: 0,
    total_votes_cast_count: 8900,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
    fewer_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
  },
  political_group_votes: [
    {
      number: 1,
      total: 3200,
      candidate_votes: [
        {
          number: 1,
          votes: 600,
        },
        {
          number: 2,
          votes: 550,
        },
        {
          number: 3,
          votes: 500,
        },
        {
          number: 4,
          votes: 500,
        },
        {
          number: 5,
          votes: 500,
        },
        {
          number: 6,
          votes: 550,
        },
      ],
    },
    {
      number: 2,
      total: 2300,
      candidate_votes: [
        {
          number: 1,
          votes: 500,
        },
        {
          number: 2,
          votes: 350,
        },
        {
          number: 3,
          votes: 400,
        },
        {
          number: 4,
          votes: 300,
        },
        {
          number: 5,
          votes: 300,
        },
        {
          number: 6,
          votes: 450,
        },
      ],
    },
    {
      number: 3,
      total: 1500,
      candidate_votes: [
        {
          number: 1,
          votes: 400,
        },
        {
          number: 2,
          votes: 100,
        },
        {
          number: 3,
          votes: 200,
        },
        {
          number: 4,
          votes: 150,
        },
        {
          number: 5,
          votes: 300,
        },
        {
          number: 6,
          votes: 350,
        },
      ],
    },
    {
      number: 4,
      total: 1200,
      candidate_votes: [
        {
          number: 1,
          votes: 300,
        },
        {
          number: 2,
          votes: 150,
        },
        {
          number: 3,
          votes: 200,
        },
        {
          number: 4,
          votes: 200,
        },
        {
          number: 5,
          votes: 100,
        },
        {
          number: 6,
          votes: 250,
        },
      ],
    },
    {
      number: 5,
      total: 700,
      candidate_votes: [
        {
          number: 1,
          votes: 300,
        },
        {
          number: 2,
          votes: 300,
        },
        {
          number: 3,
          votes: 50,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 50,
        },
      ],
    },
  ],
  polling_station_investigations: {
    admitted_voters_recounted: [],
    investigated_other_reason: [],
    ballots_recounted: [],
  },
  number_of_voters: 11158,
};

export const committee_session: CommitteeSession = {
  id: 11,
  number: 1,
  election_id: 11,
  status: "completed",
  location: "",
  start_date_time: "",
};

export const election: ElectionWithPoliticalGroups = {
  id: 11,
  name: "Election < 19 seats & Drawing lots, Candidate",
  committee_category: "CSB",
  election_id: "GR2026_Juinen",
  location: "Juinen",
  domain_id: "0035",
  category: "Municipal",
  sub_category: "GR1",
  number_of_seats: 15,
  number_of_voters: 1,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  political_groups: [
    {
      number: 1,
      name: "GROEP 8",
      candidates: [
        {
          number: 1,
          initials: "İ.",
          first_name: "İlknur",
          last_name: "Wiertz",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 3,
          initials: "D.P.K.",
          first_name: "Damian",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 4,
          initials: "S.O.",
          first_name: "Sammie",
          last_name: "Katsma",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 5,
          initials: "F.G.",
          first_name: "Jory",
          last_name: "Philippen",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 6,
          initials: "J.W.Q.Y.",
          first_name: "Jelisa",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "Middelgein",
          gender: "Male",
        },
      ],
    },
    {
      number: 2,
      name: "GROEP 9",
      candidates: [
        {
          number: 1,
          initials: "R.",
          first_name: "Royce",
          last_name: "Wiertz",
          locality: "Eemstricht",
          gender: "Female",
        },
        {
          number: 2,
          initials: "N.",
          first_name: "Cornelus",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 3,
          initials: "G.",
          first_name: "Silvana",
          last_name: "Meulenkolk",
          locality: "Sluisdam",
          gender: "Female",
        },
        {
          number: 4,
          initials: "N.",
          first_name: "Nikky",
          last_name: "Arets",
          locality: "Juinen",
          gender: "Female",
        },
        {
          number: 5,
          initials: "R.A.I.",
          first_name: "Rachid",
          last_name: "Gopal",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Bart",
          last_name: "Meulenkolk",
          locality: "Hovenerwoud",
          gender: "X",
        },
      ],
    },
    {
      number: 3,
      name: "GROEP 10",
      candidates: [
        {
          number: 1,
          initials: "R.M.",
          first_name: "Ruth",
          last_name: "Katsma",
          locality: "Sluisdam",
          gender: "Male",
        },
        {
          number: 2,
          initials: "K.",
          first_name: "Eelko",
          last_name_prefix: "de",
          last_name: "Vegt",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 3,
          initials: "U.",
          first_name: "Royce",
          last_name_prefix: "van",
          last_name: "Lent",
          locality: "Juinen",
          gender: "Male",
        },
        {
          number: 4,
          initials: "D.G.",
          first_name: "Dirk-Jan",
          last_name: "Groenen",
          locality: "Lekkum",
          gender: "Female",
        },
        {
          number: 5,
          initials: "E.",
          first_name: "Esra",
          last_name_prefix: "van",
          last_name: "Jaspers-Gezen",
          locality: "Juinen",
          gender: "X",
        },
        {
          number: 6,
          initials: "M.",
          first_name: "Madelène",
          last_name: "Groenen",
          locality: "Sluisdam",
          gender: "Female",
        },
      ],
    },
    {
      number: 4,
      name: "GROEP 11",
      candidates: [
        {
          number: 1,
          initials: "W.W.",
          last_name: "Hoogstraten",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 2,
          initials: "A.I.",
          last_name_prefix: "van",
          last_name: "Bekking",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 3,
          initials: "F.",
          last_name: "Meulenkolk",
          locality: "Bloemstede",
          gender: "X",
        },
        {
          number: 4,
          initials: "D.Y.",
          last_name: "Wolfswinkel",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 5,
          initials: "G.",
          last_name: "Hoogstraten",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 6,
          initials: "K.",
          last_name: "Güneş",
          locality: "Eksterlo",
          gender: "X",
        },
      ],
    },
    {
      number: 5,
      name: "GROEP 12",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gijsbertje",
          last_name: "Wolfswinkel",
          locality: "Eemstricht",
          gender: "X",
        },
        {
          number: 2,
          initials: "R.",
          first_name: "Ruth",
          last_name: "Wolfswinkel",
          locality: "'s Gravenveen",
          gender: "X",
        },
        {
          number: 3,
          initials: "İ.",
          first_name: "İlknur",
          last_name: "Güneş",
          locality: "Eksterlo",
          gender: "X",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Kris",
          last_name: "Güneş",
          locality: "Lekkum",
          gender: "X",
        },
        {
          number: 5,
          initials: "L.",
          first_name: "Leontien",
          last_name_prefix: "den",
          last_name: "Mateman",
          locality: "Bloemstede",
          gender: "Female",
        },
        {
          number: 6,
          initials: "Q.U.E.",
          first_name: "Rachid",
          last_name: "Wiertz",
          locality: "Bloemstede",
          gender: "Female",
        },
      ],
    },
  ],
};
