import type {
  ApportionmentState,
  CandidateNomination,
  CommitteeSession,
  ElectionSummary,
  ElectionWithPoliticalGroups,
  SeatAssignment,
} from "@/types/generated/openapi";
import type { LargestRemainderAssignmentStep, UniqueHighestAverageAssignmentStep } from "../utils/steps";

export const state: ApportionmentState = {
  type: "Finalised",
  deceased_candidates: [
    {
      pg_number: 1,
      candidate_number: 11,
    },
    {
      pg_number: 1,
      candidate_number: 12,
    },
    {
      pg_number: 1,
      candidate_number: 13,
    },
    {
      pg_number: 1,
      candidate_number: 14,
    },
    {
      pg_number: 1,
      candidate_number: 15,
    },
    {
      pg_number: 1,
      candidate_number: 16,
    },
    {
      pg_number: 1,
      candidate_number: 17,
    },
    {
      pg_number: 1,
      candidate_number: 18,
    },
    {
      pg_number: 1,
      candidate_number: 19,
    },
    {
      pg_number: 1,
      candidate_number: 20,
    },
    {
      pg_number: 1,
      candidate_number: 21,
    },
    {
      pg_number: 1,
      candidate_number: 22,
    },
    {
      pg_number: 1,
      candidate_number: 23,
    },
    {
      pg_number: 1,
      candidate_number: 24,
    },
    {
      pg_number: 1,
      candidate_number: 25,
    },
    {
      pg_number: 1,
      candidate_number: 26,
    },
    {
      pg_number: 1,
      candidate_number: 27,
    },
    {
      pg_number: 1,
      candidate_number: 28,
    },
    {
      pg_number: 1,
      candidate_number: 29,
    },
    {
      pg_number: 1,
      candidate_number: 30,
    },
    {
      pg_number: 1,
      candidate_number: 31,
    },
    {
      pg_number: 1,
      candidate_number: 32,
    },
    {
      pg_number: 1,
      candidate_number: 33,
    },
    {
      pg_number: 1,
      candidate_number: 34,
    },
    {
      pg_number: 1,
      candidate_number: 35,
    },
    {
      pg_number: 1,
      candidate_number: 36,
    },
    {
      pg_number: 1,
      candidate_number: 37,
    },
    {
      pg_number: 1,
      candidate_number: 38,
    },
    {
      pg_number: 1,
      candidate_number: 39,
    },
    {
      pg_number: 1,
      candidate_number: 40,
    },
    {
      pg_number: 1,
      candidate_number: 41,
    },
    {
      pg_number: 1,
      candidate_number: 42,
    },
    {
      pg_number: 1,
      candidate_number: 43,
    },
    {
      pg_number: 1,
      candidate_number: 44,
    },
    {
      pg_number: 1,
      candidate_number: 45,
    },
    {
      pg_number: 1,
      candidate_number: 46,
    },
    {
      pg_number: 1,
      candidate_number: 47,
    },
    {
      pg_number: 1,
      candidate_number: 48,
    },
    {
      pg_number: 1,
      candidate_number: 49,
    },
    {
      pg_number: 1,
      candidate_number: 50,
    },
  ],
  lists_drawn: [],
  candidates_drawn: [],
};

export const largest_remainder_steps: LargestRemainderAssignmentStep[] = [
  {
    residual_seat_number: 1,
    change: {
      changed_by: "LargestRemainderAssignment",
      selected_list_number: 1,
      list_options: [1],
      list_assigned: [1],
      remainder_votes: {
        integer: 8,
        numerator: 0,
        denominator: 15,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 73,
          numerator: 5,
          denominator: 11,
        },
        full_seats: 10,
        residual_seats: 0,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 59,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
];

export const unique_highest_averages_steps_part_1: UniqueHighestAverageAssignmentStep[] = [
  {
    residual_seat_number: 2,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 1,
      list_options: [1],
      list_assigned: [1],
      list_exhausted: [],
      votes_per_seat: {
        integer: 67,
        numerator: 4,
        denominator: 12,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 67,
          numerator: 4,
          denominator: 12,
        },
        full_seats: 10,
        residual_seats: 1,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 59,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 3,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 2,
      list_options: [2],
      list_assigned: [2],
      list_exhausted: [],
      votes_per_seat: {
        integer: 59,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 62,
          numerator: 2,
          denominator: 13,
        },
        full_seats: 10,
        residual_seats: 2,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 59,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 4,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 3,
      list_options: [3],
      list_assigned: [3],
      list_exhausted: [],
      votes_per_seat: {
        integer: 58,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 62,
          numerator: 2,
          denominator: 13,
        },
        full_seats: 10,
        residual_seats: 2,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 58,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 5,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 4,
      list_options: [4],
      list_assigned: [4],
      list_exhausted: [],
      votes_per_seat: {
        integer: 57,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 62,
          numerator: 2,
          denominator: 13,
        },
        full_seats: 10,
        residual_seats: 2,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 57,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
];

export const unique_highest_averages_steps_part_2: UniqueHighestAverageAssignmentStep[] = [
  {
    residual_seat_number: 6,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 5,
      list_options: [5],
      list_assigned: [5],
      list_exhausted: [1],
      votes_per_seat: {
        integer: 56,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 73,
          numerator: 5,
          denominator: 11,
        },
        full_seats: 10,
        residual_seats: 0,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 28,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 56,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
  {
    residual_seat_number: 7,
    change: {
      changed_by: "UniqueHighestAverageAssignment",
      selected_list_number: 6,
      list_options: [6],
      list_assigned: [6],
      list_exhausted: [1],
      votes_per_seat: {
        integer: 55,
        numerator: 0,
        denominator: 1,
      },
    },
    standings: [
      {
        list_number: 1,
        votes_cast: 808,
        remainder_votes: {
          integer: 8,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: true,
        next_votes_per_seat: {
          integer: 73,
          numerator: 5,
          denominator: 11,
        },
        full_seats: 10,
        residual_seats: 0,
      },
      {
        list_number: 2,
        votes_cast: 59,
        remainder_votes: {
          integer: 59,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 3,
        votes_cast: 58,
        remainder_votes: {
          integer: 58,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 29,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 4,
        votes_cast: 57,
        remainder_votes: {
          integer: 57,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 28,
          numerator: 1,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 5,
        votes_cast: 56,
        remainder_votes: {
          integer: 56,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 28,
          numerator: 0,
          denominator: 2,
        },
        full_seats: 0,
        residual_seats: 1,
      },
      {
        list_number: 6,
        votes_cast: 55,
        remainder_votes: {
          integer: 55,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 55,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 7,
        votes_cast: 54,
        remainder_votes: {
          integer: 54,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 54,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
      {
        list_number: 8,
        votes_cast: 53,
        remainder_votes: {
          integer: 53,
          numerator: 0,
          denominator: 15,
        },
        meets_remainder_threshold: false,
        next_votes_per_seat: {
          integer: 53,
          numerator: 0,
          denominator: 1,
        },
        full_seats: 0,
        residual_seats: 0,
      },
    ],
  },
];

export const seat_assignment: SeatAssignment = {
  seats: 15,
  full_seats: 10,
  residual_seats: 5,
  quota: {
    integer: 80,
    numerator: 0,
    denominator: 15,
  },
  steps: [
    ...largest_remainder_steps,
    ...unique_highest_averages_steps_part_1,
    {
      change: {
        changed_by: "ListExhaustionRemoval",
        list_retracted_seat: 1,
        full_seat: false,
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 808,
          remainder_votes: {
            integer: 8,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 62,
            numerator: 2,
            denominator: 13,
          },
          full_seats: 10,
          residual_seats: 2,
        },
        {
          list_number: 2,
          votes_cast: 59,
          remainder_votes: {
            integer: 59,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 29,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 58,
          remainder_votes: {
            integer: 58,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 29,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 4,
          votes_cast: 57,
          remainder_votes: {
            integer: 57,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 28,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 5,
          votes_cast: 56,
          remainder_votes: {
            integer: 56,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 56,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 55,
          remainder_votes: {
            integer: 55,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 55,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 54,
          remainder_votes: {
            integer: 54,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 54,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 53,
          remainder_votes: {
            integer: 53,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 53,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    {
      change: {
        changed_by: "ListExhaustionRemoval",
        list_retracted_seat: 1,
        full_seat: false,
      },
      standings: [
        {
          list_number: 1,
          votes_cast: 808,
          remainder_votes: {
            integer: 8,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: true,
          next_votes_per_seat: {
            integer: 67,
            numerator: 4,
            denominator: 12,
          },
          full_seats: 10,
          residual_seats: 1,
        },
        {
          list_number: 2,
          votes_cast: 59,
          remainder_votes: {
            integer: 59,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 29,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 3,
          votes_cast: 58,
          remainder_votes: {
            integer: 58,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 29,
            numerator: 0,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 4,
          votes_cast: 57,
          remainder_votes: {
            integer: 57,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 28,
            numerator: 1,
            denominator: 2,
          },
          full_seats: 0,
          residual_seats: 1,
        },
        {
          list_number: 5,
          votes_cast: 56,
          remainder_votes: {
            integer: 56,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 56,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 6,
          votes_cast: 55,
          remainder_votes: {
            integer: 55,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 55,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 7,
          votes_cast: 54,
          remainder_votes: {
            integer: 54,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 54,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
        {
          list_number: 8,
          votes_cast: 53,
          remainder_votes: {
            integer: 53,
            numerator: 0,
            denominator: 15,
          },
          meets_remainder_threshold: false,
          next_votes_per_seat: {
            integer: 53,
            numerator: 0,
            denominator: 1,
          },
          full_seats: 0,
          residual_seats: 0,
        },
      ],
    },
    ...unique_highest_averages_steps_part_2,
  ],
  standings: [
    {
      list_number: 1,
      votes_cast: 808,
      remainder_votes: {
        integer: 8,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: true,
      full_seats: 10,
      residual_seats: 0,
      total_seats: 10,
    },
    {
      list_number: 2,
      votes_cast: 59,
      remainder_votes: {
        integer: 59,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 3,
      votes_cast: 58,
      remainder_votes: {
        integer: 58,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 4,
      votes_cast: 57,
      remainder_votes: {
        integer: 57,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 5,
      votes_cast: 56,
      remainder_votes: {
        integer: 56,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 6,
      votes_cast: 55,
      remainder_votes: {
        integer: 55,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 1,
      total_seats: 1,
    },
    {
      list_number: 7,
      votes_cast: 54,
      remainder_votes: {
        integer: 54,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
    {
      list_number: 8,
      votes_cast: 53,
      remainder_votes: {
        integer: 53,
        numerator: 0,
        denominator: 15,
      },
      meets_remainder_threshold: false,
      full_seats: 0,
      residual_seats: 0,
      total_seats: 0,
    },
  ],
};

export const candidate_nomination: CandidateNomination = {
  preference_threshold: {
    percentage: 50,
    number_of_votes: {
      integer: 40,
      numerator: 0,
      denominator: 1500,
    },
  },
  chosen_candidates: [
    {
      number: 1,
      initials: "J.X.Q.",
      first_name: "Jory",
      last_name: "Boermans",
      locality: "Sluisdam",
      gender: "X",
      list_number: 5,
      list_name: "Politieke Groep de Partij",
    },
    {
      number: 1,
      initials: "R.",
      first_name: "Renso",
      last_name: "Gopal",
      locality: "Hovenerwoud",
      gender: "X",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 9,
      initials: "N.D.",
      first_name: "Nicolaas",
      last_name: "Hoogstraten",
      locality: "Bloemstede",
      gender: "Male",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 1,
      initials: "C.G.",
      last_name: "Katsma",
      locality: "Juinen",
      gender: "Male",
      list_number: 3,
      list_name: "Kiesregelingsunie",
    },
    {
      number: 4,
      initials: "B.O.",
      first_name: "Bart",
      last_name_prefix: "van der",
      last_name: "Meulen",
      locality: "Middelgein",
      gender: "X",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 6,
      initials: "J.",
      first_name: "Nikky",
      last_name: "Oorschot",
      locality: "Sluisdam",
      gender: "X",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 2,
      initials: "X.G.M.",
      first_name: "Damian",
      last_name: "Philippen",
      locality: "Middelgein",
      gender: "Female",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 1,
      initials: "D.C.S.",
      first_name: "Dirk-Jan",
      last_name: "Prakken",
      locality: "Heemdamseburg",
      gender: "Male",
      list_number: 4,
      list_name: "Doorstemmers",
    },
    {
      number: 5,
      initials: "R.U.",
      first_name: "Ruth",
      last_name: "Prakken",
      locality: "Huisden",
      gender: "Male",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 8,
      initials: "S.",
      first_name: "Sammie",
      last_name: "Prakken",
      locality: "'s Gravenveen",
      gender: "Female",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 7,
      initials: "L.",
      first_name: "Leontien",
      last_name_prefix: "van der",
      last_name: "Spek",
      locality: "'s Gravenveen",
      gender: "Female",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 10,
      initials: "J.C.M.",
      first_name: "Tiemen",
      last_name: "Titulaer",
      locality: "'s Gravenveen",
      gender: "Female",
      list_number: 1,
      list_name: "Stem nu!",
    },
    {
      number: 1,
      initials: "J.",
      last_name_prefix: "de",
      last_name: "Vegt",
      locality: "Hovenerwoud",
      gender: "Female",
      list_number: 6,
      list_name: "STEM",
    },
    {
      number: 1,
      initials: "N.H.M.",
      first_name: "Nicolaas",
      last_name_prefix: "van de",
      last_name: "Wal",
      locality: "Middelgein",
      gender: "Male",
      list_number: 2,
      list_name: "Partij van de groepen",
    },
    {
      number: 3,
      initials: "E.K.",
      first_name: "Eelko",
      last_name: "Wiertz",
      locality: "Hoek van Zoom",
      gender: "Female",
      list_number: 1,
      list_name: "Stem nu!",
    },
  ],
  list_candidate_nomination: [
    {
      list_number: 1,
      list_name: "Stem nu!",
      list_seats: 10,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 808,
        },
      ],
      other_candidate_nomination: [
        {
          number: 2,
          votes: 0,
        },
        {
          number: 3,
          votes: 0,
        },
        {
          number: 4,
          votes: 0,
        },
        {
          number: 5,
          votes: 0,
        },
        {
          number: 6,
          votes: 0,
        },
        {
          number: 7,
          votes: 0,
        },
        {
          number: 8,
          votes: 0,
        },
        {
          number: 9,
          votes: 0,
        },
        {
          number: 10,
          votes: 0,
        },
      ],
      updated_candidate_ranking: [
        {
          number: 1,
          initials: "R.",
          first_name: "Renso",
          last_name: "Gopal",
          locality: "Hovenerwoud",
          gender: "X",
        },
        {
          number: 2,
          initials: "X.G.M.",
          first_name: "Damian",
          last_name: "Philippen",
          locality: "Middelgein",
          gender: "Female",
        },
        {
          number: 3,
          initials: "E.K.",
          first_name: "Eelko",
          last_name: "Wiertz",
          locality: "Hoek van Zoom",
          gender: "Female",
        },
        {
          number: 4,
          initials: "B.O.",
          first_name: "Bart",
          last_name_prefix: "van der",
          last_name: "Meulen",
          locality: "Middelgein",
          gender: "X",
        },
        {
          number: 5,
          initials: "R.U.",
          first_name: "Ruth",
          last_name: "Prakken",
          locality: "Huisden",
          gender: "Male",
        },
        {
          number: 6,
          initials: "J.",
          first_name: "Nikky",
          last_name: "Oorschot",
          locality: "Sluisdam",
          gender: "X",
        },
        {
          number: 7,
          initials: "L.",
          first_name: "Leontien",
          last_name_prefix: "van der",
          last_name: "Spek",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 8,
          initials: "S.",
          first_name: "Sammie",
          last_name: "Prakken",
          locality: "'s Gravenveen",
          gender: "Female",
        },
        {
          number: 9,
          initials: "N.D.",
          first_name: "Nicolaas",
          last_name: "Hoogstraten",
          locality: "Bloemstede",
          gender: "Male",
        },
        {
          number: 10,
          initials: "J.C.M.",
          first_name: "Tiemen",
          last_name: "Titulaer",
          locality: "'s Gravenveen",
          gender: "Female",
        },
      ],
    },
    {
      list_number: 2,
      list_name: "Partij van de groepen",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 59,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 3,
      list_name: "Kiesregelingsunie",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 58,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 4,
      list_name: "Doorstemmers",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 57,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 5,
      list_name: "Politieke Groep de Partij",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 56,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 6,
      list_name: "STEM",
      list_seats: 1,
      preferential_candidate_nomination: [
        {
          number: 1,
          votes: 55,
        },
      ],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 7,
      list_name: "Unie van kandidaten",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
    {
      list_number: 8,
      list_name: "Groep van de Stemmers",
      list_seats: 0,
      preferential_candidate_nomination: [],
      other_candidate_nomination: [],
      updated_candidate_ranking: [],
    },
  ],
};

export const election_summary: ElectionSummary = {
  number_of_voters: 2000,
  voters_counts: {
    poll_card_count: 1203,
    proxy_certificate_count: 2,
    total_admitted_voters_count: 1205,
  },
  votes_counts: {
    political_group_total_votes: [
      { number: 1, total: 808 },
      { number: 2, total: 60 },
      { number: 3, total: 58 },
      { number: 4, total: 57 },
      { number: 5, total: 56 },
      { number: 6, total: 55 },
      { number: 7, total: 54 },
      { number: 8, total: 52 },
    ],
    total_votes_candidates_count: 1200,
    blank_votes_count: 3,
    invalid_votes_count: 2,
    total_votes_cast_count: 1205,
  },
  differences_counts: {
    more_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
    fewer_ballots_count: {
      count: 0,
      data_entry_sources: [],
    },
  },
  polling_station_investigations: {
    admitted_voters_recounted: [],
    ballots_recounted: [],
    investigated_other_reason: [],
  },
  political_group_votes: [
    {
      number: 1,
      total: 808,
      candidate_votes: [
        {
          number: 1,
          votes: 138,
        },
        {
          number: 2,
          votes: 20,
        },
        {
          number: 3,
          votes: 55,
        },
        {
          number: 4,
          votes: 45,
        },
        {
          number: 5,
          votes: 50,
        },
        {
          number: 6,
          votes: 100,
        },
        {
          number: 7,
          votes: 60,
        },
        {
          number: 8,
          votes: 40,
        },
        {
          number: 9,
          votes: 30,
        },
        {
          number: 10,
          votes: 20,
        },
        {
          number: 11,
          votes: 50,
        },
        {
          number: 12,
          votes: 200,
        },
      ],
    },
    {
      number: 2,
      total: 60,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 2,
        },
        {
          number: 6,
          votes: 15,
        },
      ],
    },
    {
      number: 3,
      total: 58,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 2,
        },
        {
          number: 6,
          votes: 13,
        },
      ],
    },
    {
      number: 4,
      total: 57,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 3,
        },
        {
          number: 5,
          votes: 14,
        },
      ],
    },
    {
      number: 5,
      total: 56,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 16,
        },
      ],
    },
    {
      number: 6,
      total: 55,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 15,
        },
      ],
    },
    {
      number: 7,
      total: 54,
      candidate_votes: [
        {
          number: 1,
          votes: 20,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
        {
          number: 4,
          votes: 14,
        },
      ],
    },
    {
      number: 8,
      total: 52,
      candidate_votes: [
        {
          number: 1,
          votes: 32,
        },
        {
          number: 2,
          votes: 15,
        },
        {
          number: 3,
          votes: 5,
        },
      ],
    },
  ],
};

export const committee_session: CommitteeSession = {
  id: 12,
  number: 1,
  election_id: 12,
  status: "completed",
  location: "",
  start_date_time: "",
};

export const election: ElectionWithPoliticalGroups = {
  id: 12,
  name: "Election < 19 seats & List Exhaustion & Deceased Candidates",
  committee_category: "CSB",
  election_id: "GR2026_Juinen",
  location: "Juinen",
  domain_id: "0035",
  category: "Municipal",
  number_of_seats: 15,
  number_of_voters: 1,
  election_date: "2026-03-18",
  nomination_date: "2026-02-02",
  political_groups: [
    {
      number: 1,
      name: "Political Group A",
      candidates: [
        {
          number: 1,
          initials: "L.",
          first_name: "Lidewij",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Johan",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "M.",
          first_name: "Marijke",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "A.",
          first_name: "Arie",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "B.",
          first_name: "Berta",
          last_name_prefix: "van der",
          last_name: "Weijden",
          locality: "Test Location",
          country_code: "BE",
          gender: "Female",
        },
        {
          number: 7,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Oud",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 8,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 9,
          initials: "J.",
          first_name: "Johan",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 10,
          initials: "M.",
          first_name: "Marijke",
          last_name_prefix: "van den",
          last_name: "Berg",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 11,
          initials: "R.",
          first_name: "Rolf",
          last_name_prefix: "de",
          last_name: "Jong",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 12,
          initials: "K.",
          first_name: "Karin",
          last_name: "Kok",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 2,
      name: "Political Group B",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tinus",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
          country_code: "BE",
        },
        {
          number: 2,
          initials: "D.",
          last_name: "Po",
          locality: "Test Location",
          gender: "X",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Willem",
          last_name_prefix: "de",
          last_name: "Vries",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "K.",
          first_name: "Klaas",
          last_name: "Kloosterboer",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "L.",
          first_name: "Liesbeth",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 6,
          initials: "H.",
          first_name: "Henk",
          last_name_prefix: "van den",
          last_name: "Berg",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 3,
      name: "Political Group C",
      candidates: [
        {
          number: 1,
          initials: "A.",
          first_name: "Adelbert",
          last_name_prefix: "van",
          last_name: "Doorn",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "M.",
          first_name: "Margriet",
          last_name_prefix: "van der",
          last_name: "Linden",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "P.",
          first_name: "Paul",
          last_name: "Veldkamp",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sophie",
          last_name_prefix: "de",
          last_name: "Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 5,
          initials: "R.",
          first_name: "Rik",
          last_name_prefix: "de",
          last_name: "Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 6,
          initials: "N.",
          first_name: "Nico",
          last_name: "Ruiter",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 4,
      name: "Political Group D",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gerard",
          last_name: "Bogaert",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "J.",
          first_name: "Jan",
          last_name: "Stevens",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "E.",
          first_name: "Els",
          last_name: "Groot",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "B.",
          first_name: "Bart",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 5,
          initials: "F.",
          first_name: "Frits",
          last_name: "Veldman",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
    {
      number: 5,
      name: "Blanco (Smit, G.)",
      candidates: [
        {
          number: 1,
          initials: "G.",
          first_name: "Gert",
          last_name: "Smit",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "E.",
          first_name: "Eva",
          last_name: "Koster",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "L.",
          first_name: "Leon",
          last_name: "Hofman",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "S.",
          first_name: "Sophie",
          last_name: "Visser",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 6,
      name: "Political Group F",
      candidates: [
        {
          number: 1,
          initials: "D.",
          first_name: "Dirk",
          last_name: "Bakker",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "P.",
          first_name: "Piet",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "A.",
          first_name: "Annelies",
          last_name_prefix: "van",
          last_name: "Loon",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 4,
          initials: "T.J.",
          first_name: "Tessa",
          last_name: "Jansen",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 7,
      name: "Political Group G",
      candidates: [
        {
          number: 1,
          initials: "T.",
          first_name: "Tjolk",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "H.",
          first_name: "Henny",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
        {
          number: 3,
          initials: "W.",
          first_name: "Hans",
          last_name_prefix: "van der",
          last_name: "Vaart",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 4,
          initials: "T.H.",
          first_name: "Tjolkse Hendrika",
          last_name: "Hekking",
          locality: "Test Location",
          gender: "Female",
        },
      ],
    },
    {
      number: 8,
      name: "Political Group H",
      candidates: [
        {
          number: 1,
          initials: "F.",
          first_name: "Frederik",
          last_name: "Jacobse",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 2,
          initials: "T.J.",
          first_name: "Tedje Johannes",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
        {
          number: 3,
          initials: "K.",
          first_name: "Karel",
          last_name_prefix: "van",
          last_name: "Es",
          locality: "Test Location",
          gender: "Male",
        },
      ],
    },
  ],
};
