import fs, { readdirSync } from "fs";
import prettier from "prettier";

async function run() {
  let listing = readdirSync("./lib/icon/svg");

  let result = ["// Generated by ./scripts/gen_icons.js"];

  listing.forEach((file) => {
    let content = fs.readFileSync(`./lib/icon/svg/${file}`, "utf8");
    //replace kebab-case with camelCase
    content = content.replace(/-([a-z])/g, (g) => g[1].toUpperCase());

    result.push(
      `export const Icon${ucfirst(file.replace(".svg", ""))} = () => (${content});`,
    );
  });

  let s = result.join("\n");
  s = await prettier.format(s, { parser: "typescript" });
  fs.writeFileSync("./lib/icon/gen.tsx", s);
}

run().catch((e) => {
  console.error(e);
});

function ucfirst(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
