import { PollingStation } from "@/types/generated/openapi";

export const pollingStationMockData: PollingStation[] = [
  {
    id: 1,
    election_id: 1,
    name: "Op Rolletjes",
    number: 33,
    number_of_voters: undefined,
    polling_station_type: "Mobile",
    address: "Rijksweg A12 1a",
    postal_code: "1234 YQ",
    locality: "Den Haag",
  },
  {
    id: 2,
    election_id: 1,
    name: "Testplek",
    number: 34,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Teststraat 2a",
    postal_code: "1234 QY",
    locality: "Testdorp",
  },
  {
    id: 3,
    election_id: 1,
    name: "Testschool",
    number: 35,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testplein 1",
    postal_code: "1234 AB",
    locality: "Teststad",
  },
  {
    id: 4,
    election_id: 1,
    name: "Testbuurthuis",
    number: 36,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 100",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
  {
    id: 5,
    election_id: 1,
    name: "Dansschool Oeps nou deed ik het weer",
    number: 37,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Laan van Murphy 13",
    postal_code: "4444 JP",
    locality: "Twaalfsteden",
  },
  {
    id: 6,
    election_id: 1,
    name: "Testmuseum",
    number: 38,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Teststraat 2a",
    postal_code: "1234 QY",
    locality: "Testdorp",
  },
];

export const extendedPollingStationMockData: PollingStation[] = [
  ...pollingStationMockData,
  {
    id: 7,
    election_id: 1,
    name: "Test gemeentehuis",
    number: 39,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testplein 1",
    postal_code: "1234 AB",
    locality: "Teststad",
  },
  {
    id: 8,
    election_id: 1,
    name: "Test kerk",
    number: 40,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 100",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
];
