import type { PollingStationRequest } from "@/types/generated/openapi";

export const pollingStationRequestMockData: PollingStationRequest[] = [
  {
    name: "Op Rolletjes",
    number: 33,
    number_of_voters: undefined,
    polling_station_type: "Mobile",
    address: "Rijksweg A12 1a",
    postal_code: "1234 YQ",
    locality: "Den Haag",
  },
  {
    name: "Testplek",
    number: 34,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Teststraat 2a",
    postal_code: "1234 QY",
    locality: "Testdorp",
  },
  {
    name: "Testschool",
    number: 35,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testplein 1",
    postal_code: "1234 AB",
    locality: "Teststad",
  },
  {
    name: "Testbuurthuis",
    number: 36,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 100",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
  {
    name: "Dansschool Oeps nou deed ik het weer",
    number: 37,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Laan van Murphy 13",
    postal_code: "4444 JP",
    locality: "Twaalfsteden",
  },
  {
    name: "Testmuseum",
    number: 38,
    number_of_voters: 1000,
    polling_station_type: "Special",
    address: "Teststraat 2a",
    postal_code: "1234 QY",
    locality: "Testdorp",
  },
  {
    name: "Test gemeentehuis",
    number: 39,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testplein 1",
    postal_code: "1234 AB",
    locality: "Teststad",
  },
  {
    name: "Test kerk",
    number: 40,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 100",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
  {
    name: "Test winkelcentrum",
    number: 41,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 10b",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
  {
    name: "Teststation",
    number: 42,
    number_of_voters: 1000,
    polling_station_type: "FixedLocation",
    address: "Testlaan 10c",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
  {
    name: "Teststation",
    number: 43,
    number_of_voters: undefined,
    polling_station_type: "FixedLocation",
    address: "Testlaan 10d",
    postal_code: "1234 WZ",
    locality: "Testplaats",
  },
];
