use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::domain::{
    committee_session::CommitteeSessionId, data_entry::DataEntryId, election::CommitteeCategory,
    identifier::id,
};

id!(SubCommitteeId);

pub type SubCommitteeNumber = u32;

/// Sub electoral committee base entity, independent
/// of the election, committee session and data entry.
#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct SubCommittee {
    pub id: SubCommitteeId,
    #[schema(value_type = u32)]
    pub number: SubCommitteeNumber,
    pub name: String,
    pub category: CommitteeCategory,
    pub authority_id: String,
    pub authority_name: String,
    pub certificates: Vec<Certificate>,
}

#[derive(Serialize, Deserialize, ToSchema, Debug, Clone, PartialEq)]
pub struct Certificate {
    pub election_identifier: String,
    pub organizational_unit: String,
    pub common_name: String,
    pub not_before: DateTime<Utc>,
    pub not_after: DateTime<Utc>,
    pub signature_algorithm: String,
    pub public_key: String,
}

impl Certificate {
    /// Whether the validity period has ended at `now`. The `notAfter` instant itself is still valid.
    pub fn is_expired(&self, now: DateTime<Utc>) -> bool {
        now > self.not_after
    }
}

impl SubCommittee {
    /// Add a certificate, unless its public key was already added. The other certificate fields may differ.
    pub fn add_certificate(
        &mut self,
        certificate: Certificate,
    ) -> Result<Certificate, AddCertificateError> {
        if self
            .certificates
            .iter()
            .any(|stored| stored.public_key == certificate.public_key)
        {
            return Err(AddCertificateError::AlreadyAdded);
        }
        self.certificates.push(certificate.clone());
        Ok(certificate)
    }
}

/// Reasons a certificate cannot be added to a sub committee.
#[derive(Debug)]
pub enum AddCertificateError {
    /// The public key in the certificate was already added to the sub committee.
    AlreadyAdded,
}

/// Struct for creating a new subcommittee in Abacus.
///
/// This struct does not contain the internal Abacus subcommittee id, as that is
/// generated by Abacus when creating a new subcommittee.
#[derive(Serialize, Deserialize, ToSchema, Clone, Debug)]
#[serde(deny_unknown_fields)]
pub struct NewSubCommittee {
    pub number: SubCommitteeNumber,
    pub name: String,
    pub category: CommitteeCategory,
    pub authority_id: String,
    pub authority_name: String,
}

/// Sub electoral committee in a first committee session.
#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct SubCommitteeFirstSession {
    pub committee_session_id: CommitteeSessionId,
    pub id: SubCommitteeId,
    #[schema(value_type = u32)]
    pub number: SubCommitteeNumber,
    pub name: String,
    pub authority_id: String,
    pub authority_name: String,
    pub data_entry_id: DataEntryId,
}

#[cfg(test)]
mod tests {
    use chrono::TimeZone;

    use super::*;

    #[test]
    fn test_certificate_is_expired() {
        let certificate = Certificate {
            election_identifier: "GR2026_TestLocation".to_string(),
            organizational_unit: "Abacus 1.1.0".to_string(),
            common_name: "Gemeente Test Location".to_string(),
            not_before: Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap(),
            not_after: Utc.with_ymd_and_hms(2026, 6, 18, 0, 0, 0).unwrap(),
            signature_algorithm: "RSA 4096-bit".to_string(),
            public_key: String::new(),
        };

        assert!(!certificate.is_expired(Utc.with_ymd_and_hms(2026, 3, 18, 0, 0, 0).unwrap()));
        assert!(!certificate.is_expired(certificate.not_after));
        assert!(certificate.is_expired(Utc.with_ymd_and_hms(2026, 6, 18, 0, 0, 1).unwrap()));
    }

    #[test]
    fn test_sub_committee_add_certificate() {
        let psb9101 = Certificate {
            election_identifier: "GR2026_TestLocation".to_string(),
            organizational_unit: "Abacus 1.1.0".to_string(),
            common_name: "Gemeente Test Location".to_string(),
            not_before: Utc.with_ymd_and_hms(2026, 10, 1, 0, 0, 0).unwrap(),
            not_after: Utc.with_ymd_and_hms(2026, 12, 31, 0, 0, 0).unwrap(),
            signature_algorithm: "RSA 4096-bit".to_string(),
            public_key: "first public key".to_string(),
        };
        let psb9101_other_key = Certificate {
            public_key: "second public key".to_string(),
            ..psb9101.clone()
        };
        let mut sub_committee = SubCommittee {
            id: SubCommitteeId::from(911),
            number: 1,
            name: "GSB Test Location".to_string(),
            category: CommitteeCategory::GSB,
            authority_id: "9101".to_string(),
            authority_name: "Test Location".to_string(),
            certificates: vec![],
        };

        let added = sub_committee.add_certificate(psb9101.clone()).unwrap();
        assert_eq!(added, psb9101.clone());
        assert_eq!(sub_committee.certificates, vec![added]);

        assert!(matches!(
            sub_committee.add_certificate(psb9101.clone()),
            Err(AddCertificateError::AlreadyAdded)
        ));
        assert_eq!(sub_committee.certificates.len(), 1);

        // A different certificate with the same public key is also a duplicate
        let same_key = Certificate {
            organizational_unit: "OSV2020-U".to_string(),
            not_before: Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap(),
            ..psb9101.clone()
        };
        sub_committee.certificates = vec![same_key.clone()];
        assert!(matches!(
            sub_committee.add_certificate(psb9101.clone()),
            Err(AddCertificateError::AlreadyAdded)
        ));
        assert_eq!(sub_committee.certificates, vec![same_key]);

        assert!(sub_committee.add_certificate(psb9101_other_key).is_ok());
        assert_eq!(sub_committee.certificates.len(), 2);
    }
}
