export * from "./PollingStationNumber";
export * from "./WorkStationNumber";
export * from "./BadgeCorrection.tsx";
export * from "./BadgeDefinitive.tsx";
export * from "./BadgeDifference.tsx";
export * from "./BadgeExtraEntry.tsx";
export * from "./BadgeFirstEntry.tsx";
export * from "./BadgeObjections.tsx";
export * from "./BadgeSecondEntry.tsx";
