name: Codecov

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - release-*

permissions:
  contents: read
  pull-requests: write

env:
  TZ: "Europe/Amsterdam"

jobs:
  backend-coverage:
    name: Backend coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      CARGO_TERM_COLOR: always
      SQLX_OFFLINE: "true"
      BINSTALL_DISABLE_TELEMETRY: "true"
      # Branch coverage requires Rust nightly: https://github.com/taiki-e/cargo-llvm-cov/issues/8
      RUSTUP_TOOLCHAIN: nightly-2026-07-10
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Rust Nightly
        shell: bash
        run: rustup toolchain install "$RUSTUP_TOOLCHAIN"
      - name: Cargo cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          workspaces: "backend -> target"
          cache-bin: "false"
      - name: Install Binstall
        uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # main
      - name: Install cargo-llvm-cov
        run: cargo binstall cargo-llvm-cov
      - name: Install Nextest
        run: cargo binstall cargo-nextest
      - name: Symlink sqlx test directory to /dev/shm
        run: mkdir -p target /dev/shm/sqlx && rm -rf target/sqlx && ln -s /dev/shm/sqlx target/sqlx
      - name: Run tests with coverage
        run: cargo llvm-cov nextest --workspace --branch --profile ci --features embed-typst,airgap-detection --cobertura --output-path ./target/llvm-cov-target/codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Backend Nextest Coverage
          files: backend/target/llvm-cov-target/codecov.json
          disable_search: true
          fail_ci_if_error: true
      - name: Report disk space
        run: df -h

  frontend-coverage:
    name: Frontend coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - name: Install pnpm
        run: >
          npm install --global corepack@latest &&
          corepack enable &&
          corepack prepare pnpm@latest-11 --activate
      - name: Install dependencies
        run: pnpm install
      - name: Run Vite build to report bundle size
        run: pnpm vite build --config vite.config.ts
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run tests with coverage
        run: pnpm vitest run --coverage
        env:
          CHROMIUM_CHANNEL: chrome
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Frontend Vitest Coverage
          files: frontend/coverage/coverage-final.json
          disable_search: true
          fail_ci_if_error: true
