name: Frontend

on:
  push:
  workflow_dispatch:

env:
  API_MODE: msw

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install
      - name: Check formatting
        run: npx prettier --check .
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: e2e test install
        run: npx playwright install --with-deps
      - name: e2e test
        run: npm run e2e
      - name: Build
        run: npm run build
