name: Sigrid Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    if: github.repository == 'kiesraad/abacus'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@506d05c0bdc4b827768ccf8e2ca510322b3fcbac # main
        with:
          customer: kiesraad
          system: abacus
          convert: rust
          capability: maintainability,osh,security
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
