name: Sigrid PR Feedback

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  sigridci:
    if: "!github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@855a10ef800b17214751c0c494cc0e20fe5343ca # main
        with:
          customer: kiesraad
          system: abacus
          convert: rust
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
      - name: "Sigrid PR feedback"
        uses: mshick/add-pr-comment@8e4927817251f1ff60c001f04568532b38e0b4a0 # v3.11.0
        if: always()
        with:
          message-id: sigrid
          message-path: sigrid-ci-output/feedback.md
