name: Sigrid Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    if: github.repository == 'kiesraad/abacus'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@8f05c5bd3d3a90a9972faca536ffab14749c4968 # main
        with:
          customer: kiesraad
          system: abacus
          convert: rust
          capability: maintainability,osh,security
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
