name: Sigrid Publish

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  sigridci:
    if: github.repository == 'kiesraad/abacus'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@49ea84c5a1f67cd72c8f61533f7b00e0a5f9bee8 # main
        with:
          customer: kiesraad
          system: abacus
          convert: rust
          capability: maintainability,osh,security
          publishonly: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
